### ISSUE TITLE
Dupping glitch

### ISSUE THREAD

**Issue by Skyphiler** [CalaMariGold/Rebirth-Of-The-Night#10]
Reppro Step:
1-put your backpack(wearable backpack) down 
2-put Item in it 
3-Shift break it to put it back on your back 
4-go to a armor stand (minecraft) and Shift-right click to put all equipment on the armor stand
5-all item in backpack fall on the ground
6-Shift-right click the armor stand again to get your backpack back
7-item are now in your inventory and in the backpack
8-STONK!!!

**Comment by CalaMariGold** [comment]
Likely going to remove that backpack mod in favor of Quark's backpack addon. It's much more vanilla friendly, I think, but has it's downsides. I'll keep this issue open until I switch to quark's. If I don't switch, Ill report this to the mod developer, unless you want to copy and paste this issue onto the wearable backpacks issues

**Comment by SandwichHorror** [comment]
removed wearable backpacks
