### ISSUE TITLE
https://paste.dimdev.org/ikudobasaj.mccrash[CRASH]

### ISSUE THREAD

**Issue by Thermal3301** [CalaMariGold/Rebirth-Of-The-Night#101]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
I started the game for the first time after placing the optifine jar file inside the mod folder. Before the mod loaded i was met with a message that an error occured during start up preventing minecraft from starting 'Pam's HarvestCraft' was the mod which cause this eror. I was running the native launcher with 8GB of ram allocated.

[EDIT I also added a mod called Chinjufu mod which is a 1.12.2  mod]
**To Reproduce**
Steps to reproduce the behavior:N/A

**Crash Log**
https://paste.dimdev.org/ikudobasaj.mccrash

**Info (please complete the following information):**
 - Modpack Version: 2.76.1
 - Server or Singleplayer: N/A
 - Version the world was created on: N/A

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.
![Minecraft](https://user-images.githubusercontent.com/61636843/75615922-fa62c400-5b41-11ea-8c66-c00dabe0666e.png)

**Comment by SandwichHorror** [comment]
Have you modified the pack in any way? This happens if the maximum number of block IDs is exceeded. Since no one else has reported this problem before, I have to assume you've installed some other mod - possibly one which adds a large number of new blocks like Chisel.

**Comment by CalaMariGold** [comment]
Remove the mod you added.
