### ISSUE TITLE
[CRASH] Suspected Mods: CraftTweaker2 (crafttweaker), CraftTweaker JEI Support (crafttweakerjei), CT-GUI (ctgui)

### ISSUE THREAD

**Issue by xRASLER13** [CalaMariGold/Rebirth-Of-The-Night#102]
when you are crafting a message error start spamming , saying that theres is a problem with CraftTweaker2 

https://paste.dimdev.org/hutukaxeda.mccrash

**Comment by SandwichHorror** [comment]
Please use the issue template.
