### ISSUE TITLE
[CRASH] Unexplicable Crash via 'Rats'

### ISSUE THREAD

**Issue by MaybeNotACow** [CalaMariGold/Rebirth-Of-The-Night#103]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
Upon loading into my SP world, after an indeterminable amount of time , the mod 'Rats' causes me to crash. Presumably due to some spawning of a Rat (as I have not tamed or invested myself into the Rats additions

**To Reproduce**
TBD
**Crash Log**
Click "Get Link" from the crash and paste it here. Or post the log if it's a server.

https://paste.dimdev.org/yabebapoza.mccrash

**Info (please complete the following information):**
 - Modpack Version: 2.76.1
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.76

**Additional context**
N/A

**Comment by CalaMariGold** [comment]
I think @SandwichHorror attempted to fix this in the next version. If it still occurs on the latest update, reopen this issue.
