### ISSUE TITLE
[BUG] Enderman spawn cap

### ISSUE THREAD

**Issue by penguinbob1** [CalaMariGold/Rebirth-Of-The-Night#104]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Enderman are spawning without a cap in the end, have around 1000 enteties while I'm in out in the void a bit away from the island.

**To Reproduce**
Steps to reproduce the behavior: enter the end, tried restarting, letting them despawn reloading, nothing works.

**Expected behavior**
Normal spawning and cap.

**Info (please complete the following information):**
 - Modpack Version: last
 - Server or Singleplayer: singleplauer
 - Version the world was created on: last

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by CalaMariGold** [comment]
"last" doesn't make any sense. The enderman spawn bug has been fixed a few versions ago.
