### ISSUE TITLE
[BUG] Items disappearing

### ISSUE THREAD

**Issue by donutbunny** [CalaMariGold/Rebirth-Of-The-Night#107]
**Describe the bug**
hello, my boyfriend and i were playing and whenever we dropped items to each other the item would disappear, not all items that hit the ground disappear because items when we killed things or died stayed, but only if we dropped them using "Q".

**To Reproduce**
-be on a multiplayer server
-player A drops something on the ground using the drop key ("Q")
-item disappears [BUG]

**Expected behavior**
i expected the item to not disappear, expected the item to be dropped by one of us and be able to be picked up by either of us.

**no screenshots**

**Info:**
 - Modpack Version: 2.76.1
 - Server or Singleplayer: Multiplayer Server
 - Version the world was created on: 1.12.2

**no additional context**

**Comment by CalaMariGold** [comment]
I'll try to reproduce this. If I can't, I'm gonna need more information. Try restarting the server, updating the modpack, etc...
