### ISSUE TITLE
[BUG] Not able to craft torches and sticks

### ISSUE THREAD

**Issue by TokkPython** [CalaMariGold/Rebirth-Of-The-Night#108]
**Describe the bug**
While I was playing this modpack, nothing abnormal was really happening but after I made a new world and played it for about a real-time day, I closed the game and go to sleep, after reopening the game the next day, the torches and sticks are uncraftable. Torches can't be made using normal coal and sticks anymore and sticks can't be made by using normal wooden planks.

**To Reproduce**
1. Be in a normal world.
2. Gather planks and/or coal
3. Attempt to craft sticks by using planks on a crafting table or inventory's crafting grid. Also, attempt to craft torches by using sticks (from creative or tree drops) and coal on a crafting table or inventory's crafting grid.
4. Output is empty for both occasions. [BUG]

**Expected behavior**
I expect to see the torches and sticks to be craftable like normal minecraft because I've done it before in the past, playing on this modpack.

**Screenshots**
![q](https://user-images.githubusercontent.com/34391746/75879977-0060e980-5e4f-11ea-8731-fd82165b7b28.PNG)
![o](https://user-images.githubusercontent.com/34391746/75879986-048d0700-5e4f-11ea-8aff-e51ed1d746cf.PNG)
![p](https://user-images.githubusercontent.com/34391746/75879988-05be3400-5e4f-11ea-9931-70ac8f85fb90.PNG)

**Info**
 - Modpack Version: 2.76.1
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 1.12.2

**Additional context**
I was playing this modpack using Twitch. On this particular world, I wasn't playing on my own. I was actually playing with a friend on my singleplayer world (LAN). We found out that the torches and sticks can't be crafted normally which makes us really frustrated because we've been playing WITH craftable torches for a while and this makes the game unreasonably complicated.

We've tried out the following:
1. Rejoining the world again
2. Restarting Minecraft
3. Restarting the computer
4. Creating a new world (Creative and Survival)
5. Copy and paste the world on the desktop and reinstall the modpack and put it back.
6. Playing on an old Rebirth of the Night world.

**Comment by CalaMariGold** [comment]
Try updating the pack. Restart the game. Let me know if this has been fixed.
