### ISSUE TITLE
[CRASH] SnowRealMagic error (6x reported in Discord)

### ISSUE THREAD

**Issue by kil0byt3** [CalaMariGold/Rebirth-Of-The-Night#109]
**Describe the crash**
Just wanted to make sure you guys had this tracked, been seeing it all over Discord. My tag is kilo#6969

World crashes on re-entry after update to 2.76.2, with crash log linked below. World is unable to be recovered. 

**To Reproduce**

Enter world after update to 2.76.2 with snow from SnowRealMagic on the ground.

**To Fix**

Reinstalling [Snow Real Magic](https://www.curseforge.com/minecraft/mc-mods/snow-real-magic) fixes issue for 5x Discord reporters.

**Crash Log**
https://paste.dimdev.org/ovewurehar.mccrash

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Singleplayer, LAN, MP
 - Version the world was created on: 2.76.1 or below.

**Additional context**
Tile entities from Snow Real Magic incorrectly removed by Forge/could not be removed by Forge after removing that mod.

**Comment by MaybeNotACow** [comment]
Similar issue, will submit log here. Apologies for any issues!

---

https://paste.dimdev.org/doyacanuqe.mccrash
