### ISSUE TITLE
[CRASH] Wither fight crash

### ISSUE THREAD

**Issue by grJDh** [CalaMariGold/Rebirth-Of-The-Night#110]
**Describe the crash**
Can't fight Wither. I summon him, fight 1-2 minutes and game crashes.
Did it 4 times already.

**To Reproduce**
Summon and fight Wither.

**Crash Log**
Last 2 crash reports:
https://paste.dimdev.org/vewatuzoqu.mccrash
https://paste.dimdev.org/vimugajidu.mccrash

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Single
 - Version the world was created on: 2.76.1, but chunks are new - generated on 2.76.2

**Additional context**
Tried it in The Nether and Overworld both, same result.
Was able to kill it 1 time on 4th try, but all loot fell into lava, so i tried kill him again and it crashed.

**Comment by grJDh** [comment]
No, but those last 2 times I tried to fight him in creative, just for it to be easier after 2 fails, maybe that's it?

**Comment by SandwichHorror** [comment]
Apologies for that. There's a bug where the skeletons summoned by the wither want to retaliate when hit by friendly fire, but cannot, and crash instead. It'll be fixed in 2.77.
