### ISSUE TITLE
[BUG]Black Dragon Scale crafting recipe not in game

### ISSUE THREAD

**Issue by hyang336** [CalaMariGold/Rebirth-Of-The-Night#111]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Black Dragon Scale crafting recipe not in game.

**To Reproduce**
Have nether star, cracked black dragon scale, and ender dragon scale, put it in crafting table, nothing. You also cannot see the recipe in JEI

**Expected behavior**
Should be able to craft it with nether star, cracked black dragon scale, and ender dragon scale

**Screenshots**
N/A

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.76.1

**Additional context**
N/A

**Comment by CalaMariGold** [comment]
Should be fixed next update
