### ISSUE TITLE
[BUG] item frame bug

### ISSUE THREAD

**Issue by zirza** [CalaMariGold/Rebirth-Of-The-Night#113]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
trying to place an item on an item frame while having an off-hand sword will knock down the item frame and destroy the item you tried to put in the item frame
**To Reproduce**

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 
 - Server or Singleplayer:
 - Version the world was created on:

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by SandwichHorror** [comment]
Intended. Right-clicking prioritizes use of offhand over any other function.
To avoid, simply remove the item from your offhand.

**Comment by zirza** [comment]
Yes I know but if you accidentally do it like me you will lose the item you try to put into the frame. It disappears.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
