### ISSUE TITLE
[BUG] Living Tools creates ghost blocks

### ISSUE THREAD

**Issue by Sumeroo** [CalaMariGold/Rebirth-Of-The-Night#114]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Using a pickaxe with the living tools enchantment tends to create ghost blocks. The blocks are not visible but can be collided with and reappear if you try to place another block or right click the area. A toast also appears saying that it is living tools causing the problem.

**To Reproduce**
Just mining should create them occasionally, but a consistent way I found was instant mining a block. In my case it was using a diamond pick to instant mine greenhouse glass. The pick had silk touch, unbreaking 2, efficiency 3, and living. Living was at level 16.

**Expected behavior**
The glass should break and drop itself because of silk touch. 

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.76.2

**Additional context**
Here is a pastebin of the error: https://paste.dimdev.org/zolivigisa.mccrash

**Comment by CalaMariGold** [comment]
Living enchantment will be disabled from all weapons next update except the lights and darks edge
