### ISSUE TITLE
[CRASH] in-game error report. Big lag spikes on my server (client side issue)

### ISSUE THREAD

**Issue by Johnsonk2** [CalaMariGold/Rebirth-Of-The-Night#115]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
No game crashes just in-game crash/error reports whilst having big lag spikes. no one else on my server is effected and I'm just sat in my base as usual nothing has happened that would cause it.

**To Reproduce**
Steps to reproduce the behavior: not a clue

**Crash Log**
https://paste.dimdev.org/lunipitoza.mccrash
and https://paste.dimdev.org/urizupiyuv.mccrash

**Info (please complete the following information):**
 - Modpack Version: latest - 2.76.2
 - Server or Singleplayer: server but client side issue (everyone else is fine)
 - Version the world was created on: 2.76.2

**Additional context**
no idea

**Comment by CalaMariGold** [comment]
Those crash logs don't tell me much unfortunately. Try decreasing the view distance in server.properties to help with lag.
