### ISSUE TITLE
[CRASH] Private Server keeps crashing. 

### ISSUE THREAD

**Issue by TreeThighs** [CalaMariGold/Rebirth-Of-The-Night#118]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
The server just closes

**To Reproduce**
Steps to reproduce the behavior: Start the server, play after about 10 minutes max then the server crashes and closes itself

**Crash Log**
https://pastebin.com/PYfyEASB

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Server
 - Version the world was created on: 2.72

**Additional context**
I've tried increasing the RAM to see if that would fix the problem server was running smoothing as per usual and it would still crash after about 10 minutes of playing on it.

**Comment by SandwichHorror** [comment]
Try reinstalling the Snow: Real Magic mod. Everyone on the server will need to do it as well.

**Comment by TreeThighs** [comment]
@SandwichHorror 
Would I just take the mod out of the folder, run the server, then put the mod back in?

**Comment by CalaMariGold** [comment]
Think snow real magic needs to be added back in, since youre on 2.76.2
