### ISSUE TITLE
[BUG] Ender's Flower- Infinite Source of XP 

### ISSUE THREAD

**Issue by ShawtgunHobo** [CalaMariGold/Rebirth-Of-The-Night#119]
**Describe the bug**
Upon finding a floating end island, and repeatedly right clicking an Ender's Flower, an infinite amount of XP orbs can be produced. This was encountered in Survival mode, LAN, and resulted in around 30 levels for each player before players stopped. The plant still remained unchanged throughout.

**To Reproduce**
I tried to reproduce this in single player by planting and growing an ender's flower, but nothing happened upon right clicking. I am unsure if the bug is only confined to the world-generated islands, or if it is due to LAN only.

**Expected behavior**
As above.

**Screenshots**
None captured. 

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: 'Singleplayer' world, hosted on LAN.
 - Version the world was created on: 2.75(?)

**Additional context**
N/A.

**Comment by CalaMariGold** [comment]
Strange, sounds like an issue for the Endreborn github, which isn't updating their mod anymore afaik

**Comment by kil0byt3** [comment]
Opened ER issue, waiting

**Comment by kil0byt3** [comment]
Fixed in next ER update. https://github.com/EleC0TroN/ER/issues/4#issuecomment-612453227
