### ISSUE TITLE
[BUG] Bone slabs not dropping when mining 

### ISSUE THREAD

**Issue by sspazzy** [CalaMariGold/Rebirth-Of-The-Night#120]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Bone slabs disappear when mining them.

**To Reproduce**
Place down 2 bone slabs as to form a full block and mine to pick them back up..
**Expected behavior**
2 bone slabs are supposed to drop. Neither do.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.76.1

**Additional context**
When mining one bone slab it will drop but both of them as a whole block they just get deleted. Restarting my world did not fix it.

**Comment by kil0byt3** [comment]
Should be fixed in 2.77, please reopen if not
