### ISSUE TITLE
[BUG] mounting hippogryph with shield in offhand disables right-clicking while holding anything in either hand

### ISSUE THREAD

**Issue by Swordsyke** [CalaMariGold/Rebirth-Of-The-Night#121]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
After riding a hippogryph that you got onto with a shield equipped in your offhand and nothing in your main hand, right-clicking on interactive blocks such as chests while holding anything in either hand is disabled.

**To Reproduce**
Right click on a hippogryph while holding a shield in your offhand and nothing in your main hand. Ride it around and land. Then try to use a chest while holding an item in either hand. For reference, I had a gem forged shield and my hippogryph had diamond armor, a chest, and a saddle on it.

**Expected behavior**
I expected the chest to open regardless of holding items in my hands.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.76.2

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by CalaMariGold** [comment]
I don't think you should be able to interact with containers when riding an entity. Not completely sure though

**Comment by Swordsyke** [comment]
I said "after riding," and by that I meant "after you have dismounted."

**Comment by kil0byt3** [comment]
Lag/TPS issue with Ice and Fire, should be solved in next version of I&F

**Comment by Swordsyke** [comment]
You are incorrect. I could interact with containers when I was holding nothing in both hands, but could not interact with them while holding anything in either hand. This was not a lag/TPS issue because that would mean I wouldn't have been able to interact with them regardless of holding items in my hands.

**Comment by kil0byt3** [comment]
This is confirmed issue with player position not saving correctly in the latest I&F, nothing we can do to fix until mod version releases
