### ISSUE TITLE
[CRASH] The weird "Fatally missing registry entries" issue from the 2.76.2 server pack - round 2

### ISSUE THREAD

**Issue by kil0byt3** [CalaMariGold/Rebirth-Of-The-Night#122]
**Describe the crash**

Big thanks to Emil#5915 on Discord, who had this issue and helped me troubleshoot on his end for a few hours, leading me to the problematic mod.

I helped Mari with this previously when we figured out the server pack for 2.76.2. It worked for me but not her, and then she downloaded my server pack and it worked for her - leading us to think it was just that instance of the server pack. It's apparently more common and others have it, even with a fresh 2.76.2 server pack from our Curseforge.

It's a conflict between Redstone++ and FastFurnace/FastWorkbench

It's caused when starting a new world _on a server with Redstone++ installed_. Server has no problems, no crashing, but when you join the game on a client the error message is received. The server then crashes.

When Redstone++ is removed on server and client, and server is started, the world is joinable, then you can re-add the mod to server and client and join fine. 

You can also solve with creating an SP world and then trying to join server.

**To Reproduce**

Sporadic. Create a new server and new world with Redstone++ enabled, and randomly will receive this error depending on unknown factors. Needs testing and a solid reproduction. 

**Crash Log**
Unfortunately no logs received from testing - but will test and try to get some myself. 

![Client error message](https://user-images.githubusercontent.com/39413400/76569834-4df1dd80-6471-11ea-91dd-6e624314e911.png)

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Server, yet client has error
 - Version the world was created on: 2.76.2

**Additional context**
Will assign this one to myself when Mari gives me access to GitHub later!

**Comment by CalaMariGold** [comment]
In any case, we should remove Redstone++ if this issue persists.
