### ISSUE TITLE
[CRASH] Throwing Cockatrice Eggs crash animania

### ISSUE THREAD

**Issue by FkArts** [CalaMariGold/Rebirth-Of-The-Night#123]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
I tossed a cockatrice egg that I received from one of my rock hens. It works fine when i received no chick but it crashed when I did.

**To Reproduce**
1. Get cocktrice egg from hen.
2. Toss.
3. Crash when chick is produced

**Crash Log**
https://paste.dimdev.org/eyosavopeh.mccrash

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.76.2

**Additional context**
I have a feeling that its drawing on chicks chances from base Minecraft itself to determine if I get one and how many. Animania removes this and this may have been something that Fire and Ice depended on. This leaves the only taming option to best a cockatrice in a staring contest.

**Comment by SandwichHorror** [comment]
Should be fixed in the next update. I won't close until I'm sure it consistently does not crash.
