### ISSUE TITLE
[BUG] wooden buckets smelt infinite items in furnaces

### ISSUE THREAD

**Issue by emeraldspark** [CalaMariGold/Rebirth-Of-The-Night#125]
**Describe the bug**
a wood bucket will smelt infinite items if put in a normal furnace

**To Reproduce**
Steps to reproduce the behavior: 1. get a wooden bucket 2. put it in the lower slot of a furnace 3. smelt items 4. profit

**Expected behavior**
i expected the bucket to go away eventually but am now regretfully abusing this bug to smelt ores without using precious coal

**Screenshots**
![image](https://user-images.githubusercontent.com/62184753/76687520-ca5ffa00-65f2-11ea-910b-5f6a724f8489.png) a bucket in a furnace

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: server
 - Version the world was created on: 2.76.1

**Additional context**
help

**Comment by kil0byt3** [comment]
Weird. Can't see why that would happen, and it's only supposed to be 1 item anyways, so I've just disabled burning these for now, thanks for the report!
