### ISSUE TITLE
[CRASH] Dynamic Tress causing crashes continuesly

### ISSUE THREAD

**Issue by Lucaya88** [CalaMariGold/Rebirth-Of-The-Night#128]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
The world is loading and after and when I spawn in shortly after, sometimes it works for a few seconds, the worlds crashes with the Dynamic tress being the cause.

**To Reproduce**
Loading into the world and let chunks loading.

**Crash Log**
https://paste.dimdev.org/kiloquhequ.mccrash

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Singleplayer:
 - Version the world was created on: 2.76.2

**Additional context**
I already saw a post about this problem, but the solutions does not seems to work for me.

**Comment by CalaMariGold** [comment]
Dynamic Trees is known to cause a few crashes. I would report this issue to their github. Create a new world for now.

**Comment by kil0byt3** [comment]
Issue exists on DTrees Github, waiting

**Comment by kil0byt3** [comment]
Should be fixed in latest version of DT/will be fixed in next version of RotN https://github.com/ferreusveritas/DynamicTrees/issues/417#issuecomment-631023757
