### ISSUE TITLE
[BUG] Multiple Crafting Errors

### ISSUE THREAD

**Issue by MutantBacon** [CalaMariGold/Rebirth-Of-The-Night#131]
Multiple early game recipes such as the Re-factory kiln, anvils, and other things do not work

Attempt to create a refactory kiln using the brick recipe

I wanted a refactory kiln

**Screenshots**
(https://user-images.githubusercontent.com/62267402/76806351-82d69b00-67b7-11ea-9d79-e719987efe67.png)

 - Modpack Version: 2.76.2
Single player
 - Version the world was created on: 2.76.2

The ore dictionary could have messed it up, I also installed the chisel mod and ancient warfare however I don't believe that these would have messed it up

**Comment by SandwichHorror** [comment]
Try again without the Chisel mod. We don't provide official support for personally-modified versions of the modpack.
