### ISSUE TITLE
[BUG] Missing Patchouli

### ISSUE THREAD

**Issue by LemADEC** [CalaMariGold/Rebirth-Of-The-Night#132]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Missing documentation from Pyrotech due to missing Patchouli mod in the pack.

**To Reproduce**
search for the book!

**Expected behavior**
Mods coming with their documentation or quest description updated to compensate?

**Screenshots**
n/a.

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Server
 - Version the world was created on: 2.76.2

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by CalaMariGold** [comment]
Intended

**Comment by Foreck1** [comment]
To give some further information, most items from pyrotech are altered in some way or another, a lot completely removed (including the book itself), this is compensated by giving description tabs to most of them which you should always read when looking for recipes (A scroll icon with an "i" letter)

**Comment by LemADEC** [comment]
I did miss the 'I' tab when searching how to light up the kiln.
I guess I'm more used the classic blue icon.
