### ISSUE TITLE
[BUG]Achievement for vertical windmill is given when crafting water mill. It is NOT given for crafting the vertical windmill

### ISSUE THREAD

**Issue by HutmanGaming** [CalaMariGold/Rebirth-Of-The-Night#133]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 
 - Server or Singleplayer:
 - Version the world was created on:

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by CalaMariGold** [comment]
Issue for the Better With Mods github. We can't do much about it until we rework BWM achievements, which will be awhile.

**Comment by kil0byt3** [comment]
Opened BWM issue https://gitlab.com/BetterWithMods/1.12/BetterWithMods/-/issues/1360

**Comment by democat3457** [comment]
Fixed with https://gitlab.com/BetterWithMods/1.12/BetterWithMods/-/merge_requests/976
