### ISSUE TITLE
[CRASH]Wormhole potion

### ISSUE THREAD

**Issue by PaLaS0** [CalaMariGold/Rebirth-Of-The-Night#134]
**Describe the crash**
Crashed twice when I didn't accept wormhole request.

**To Reproduce**
Have a friend use wormhole to teleport to you, do not accept it and wait around 1 minute.

**Crash Log**
[crash-2020-03-17_01.50.13-server.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4345762/crash-2020-03-17_01.50.13-server.txt)

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Server
 - Version the world was created on: 2.76.2

**Comment by CalaMariGold** [comment]
Looks like an issue for the Bountiful Baubles github.

**Comment by democat3457** [comment]
btw https://github.com/CursedFlames/BountifulBaubles/pull/32 pr

**Comment by democat3457** [comment]
Fixed in one of the 2.77.x versions.
