### ISSUE TITLE
[BUG] Sorting does not work on radiant chests

### ISSUE THREAD

**Issue by RobertK1229** [CalaMariGold/Rebirth-Of-The-Night#135]
**Describe the bug**
Attempting to sort the inventory of a radiant chest results in nothing happening.

**To Reproduce**
fill a radiant chest with items and click the sort button next to the chest inventory

**Expected behavior**
Items within chest should be sorted based on how they are when placed in vanilla chests

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Server
 - Version the world was created on: 2.74

**Comment by SandwichHorror** [comment]
Known issue. Reported to Quark and Arcane Archives developer; Arcane Archives developer said they can't do much and it's on Quark's end. Waiting on Vazkii to address the sorting.

**Comment by CalaMariGold** [comment]
Fixed in 2.77
