### ISSUE TITLE
[CRASH] Crash during recursive snow updates

### ISSUE THREAD

**Issue by RobertK1229** [CalaMariGold/Rebirth-Of-The-Night#136]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
Server crash due to a stackoverflow exception during snow update

**To Reproduce**
traversing snowy biomes, perhaps at a higher speed.

**Crash Log**
![image](https://user-images.githubusercontent.com/43769281/77005862-8db43b80-692f-11ea-9bd5-03cfb47f4b03.png)

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: server
 - Version the world was created on: 2.74

**Additional context**
Was using boot of blinding speed to traverse biome at the time of the crash. Could be relevant?

**Comment by CalaMariGold** [comment]
World was created in 2.74 so it may be an issue with Snow Real Magic. This shouldn't occur in new worlds. Reopen this issue if it does.
