### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by eliisorp** [CalaMariGold/Rebirth-Of-The-Night#137]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
i was mining down in the overworld and it said "shutting down internal server" and kicked me out of my world
also happened when i was flying in creative mode on a different world.
it only happens after some time has passed.

**To Reproduce**
?????
**Crash Log**
Click "Get Link" from the crash and paste it here. Or post the log if it's a server.
https://paste.dimdev.org/edamabahed.mccrash

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: singleplayer
 - Version the world was created on: 2.76.2

**Additional context**
pepega clap world record

**Comment by CalaMariGold** [comment]
`Entity's Vehicle: ~~ERROR~~ NullPointerException: null`

I'm thinking a Zotsypre or another entity was on top of a skeleton warrior. Or a skeleton warrior tried to hop on top of another mob and that caused a crash. We'll remove skeleton warriors using others as vehicles, if its not already disabled. @SandwichHorror
