### ISSUE TITLE
[CRASH] Living Enchantment on armor causes crash on damage tick

### ISSUE THREAD

**Issue by GoofTroop007** [CalaMariGold/Rebirth-Of-The-Night#141]
**Describe the crash**
Taking damage with the living Enchantment on a diamond helmet causes my game to crash. Any damage tick causes the crash. 

**To Reproduce**
Enchant diamond helmet with living and see if a damage tick causes a crash. 

**Crash Log**
https://paste.dimdev.org/fageloqave.mccrash

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Singleplayer/LAN
 - Version the world was created on: 2.76.2

**Additional context**
The diamond helmet is lvl 15, ~4400 xp total. I did not have this problem until then.

**Comment by CalaMariGold** [comment]
Living enchantment should be completely disabled from obtaining in the next update, except for the swords it's supposed to be on. Create a new issue if you manage to obtain a Living book in 2.77.
