### ISSUE TITLE
[BUG] Stone Shovel Gives off Light w/Builder's Modded Shaders

### ISSUE THREAD

**Issue by Fliptzy** [CalaMariGold/Rebirth-Of-The-Night#142]
**Describe the bug**
I would assume this isn't intended. A stone shovel gives off dynamic light when using Builder's Modded Shaders V2.4.1

**To Reproduce**
Install Builder's Modded Shaders and hold a stone shovel

**Expected behavior**
I expected no light to radiate from the stone shovel.

**Screenshots**
![2020-03-20_11 28 36](https://user-images.githubusercontent.com/62436296/77178870-118c3600-6a9e-11ea-95bc-20b12c29db6c.png)
![2020-03-20_11 28 43](https://user-images.githubusercontent.com/62436296/77178867-10f39f80-6a9e-11ea-85e6-6fb8ea06fa9f.png)

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.76.2

**Comment by CalaMariGold** [comment]
I'm unsure how shaders work with determining what items get light sources. I assume this is a bug with the shader and would suggest reporting that bug to the shader's author.
