### ISSUE TITLE
[BUG] Some rustic elixirs are uncraftable

### ISSUE THREAD

**Issue by Eksekk** [CalaMariGold/Rebirth-Of-The-Night#145]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Several rustic elixirs are uncraftable, namely of Regeneration and Healing (because there are no rustic honeycombs nor vanilla raw beef).

**To Reproduce**

**Expected behavior**
Either it can be brewed with ingredients that are possible to obtain (better), or remove recipe completely (please don't do that :c).

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.76.1

**Additional context**
I got the info about this bug from discord, and confirmed it in my game.

**Comment by CalaMariGold** [comment]
We will be doing an entire potion rework in a future update. We will fix this issue then.

**Comment by Kompreya** [comment]
Potion rework planned for 2.8: https://trello.com/c/eErVfIFK

I may visit these bugged recipes sooner, if time allows.

**Comment by kil0byt3** [comment]
You fixed this one yourself, pushed in 2.77 :)
