### ISSUE TITLE
[BUG] Quartz ore generates in overworld stone types (so no texture)

### ISSUE THREAD

**Issue by Eksekk** [CalaMariGold/Rebirth-Of-The-Night#146]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
In title.

**To Reproduce**
Idk.

**Expected behavior**
There shouldn't be quartz ore generated as stone variants (or maybe this is a feature? then there should be texture).

**Screenshots**

![](https://i.imgur.com/NIYfvWd.png)

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.76.1

**Additional context**
I had "nether" dungeon (with normal quartz ore, nether blocks, blaze spawners, lava etc.) generated in the Beneath, and this was near it.

**Comment by CalaMariGold** [comment]
Known issue and fixed in the next version
