### ISSUE TITLE
[SUGGESTION] Add ReAuth so you don't have to restart for a new session id

### ISSUE THREAD

**Issue by Gerdathlete** [CalaMariGold/Rebirth-Of-The-Night#147]
**Describe the issue**
After a certain period of time logged in, you receive the error "Invalid Session ID" when attempting to join a server.

**To Reproduce**
Join a server after AFK for a few hours

**Expected behavior**
Press Re-Login in the top-left corner of the multiplayer window in order to fix the issue.
(feature added by ReAuth)

**Info**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Singleplayer -- Multiplayer Login
 - Version the world was created on: 2.76.2

**Additional context**
ReAuth is available for most versions of Minecraft and allows the player to login without restarting their client.
https://www.curseforge.com/minecraft/mc-mods/reauth

**Comment by CalaMariGold** [comment]
Added in 2.77
