### ISSUE TITLE
[CRASH] Rotten Egg Crash

### ISSUE THREAD

**Issue by Eric-Cf** [CalaMariGold/Rebirth-Of-The-Night#153]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
Unclear, users were doing various things.
1. User 1 threw a rotten egg on the ground.
2. User 2 was drowning in an ocean biome ~200 blocks away
3. User 2 again was breaking ice in same ocean biome
4. User 2 logged on, loaded chunks, and instantly crashed.

**To Reproduce**
Unclear

**Crash Log**
Crash 1: 
[crash-2020-03-22_08.35.21-server.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4364861/crash-2020-03-22_08.35.21-server.txt)
Crash 2:
[crash-2020-03-22_09.01.03-server.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4364863/crash-2020-03-22_09.01.03-server.txt)
Crash 3:
[crash-2020-03-22_09.09.21-server.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4364864/crash-2020-03-22_09.09.21-server.txt)
Crash 4:
[crash-2020-03-22_09.17.21-server.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4364865/crash-2020-03-22_09.17.21-server.txt)

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Server
 - Version the world was created on: 2.76.2

**Additional context**
¯\\_(ツ)_/¯

**Comment by Eric-Cf** [comment]
Feel free to dm me on discord for more details. I check discord daily but github rarely.
I have not editted any of the configs other than adding dcintegration mod to the serverpack. 

Discord User: Coolfood#4583

**Comment by Eric-Cf** [comment]
Update: Users 1 and 2 cannot log on without immediately crashing the server.

**Comment by CalaMariGold** [comment]
I'll take a look at this. It has something to do with the rotten egg I believe

**Comment by Eric-Cf** [comment]
Update: Issue happened again. User 3 threw a rotten egg and crashed the server.
From that point on, whenever User 3 or 2 other users who were nearby at the time logged on, the server instantly crashed.
Repeated ~7 times before it seemed to resolve

**Comment by SandwichHorror** [comment]
Fixed in 2.77.
