### ISSUE TITLE
Tome of Golemancy Guidebook recipe issue.

### ISSUE THREAD

**Issue by ThreeForths** [CalaMariGold/Rebirth-Of-The-Night#156]
The Tome of Golemancy book has the wrong crafting recipe written down in it.

It says, to craft a Golem spell you need - Feather, Black Dye, Paper, Redstone -

But when you go to craft it, you will be bamboozled as to why the recipe isnt working, only to find out you need Magic Powder as well.

The book needs to have its recipe updated.

**Comment by CalaMariGold** [comment]
I don't believe there's a way to edit that book, so we will remove it. Thanks for letting us know!
