### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by pesdro** [CalaMariGold/Rebirth-Of-The-Night#157]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
the crash happens when i craft green schist bricks

**To Reproduce**
using the stone cutter with 2 or more green schist, select the green schist brick and use Shift click to get the all result. the crash happens and you lose the inventory items

**Crash Log**
https://paste.dimdev.org/ofilaqekum.mccrash

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: singleplayer
 - Version the world was created on:  2.76.2

**Additional context**
i haven't tested with other types of stones

**Comment by CalaMariGold** [comment]
Duplicate of #24
