### ISSUE TITLE
Crash with Airship Mod

### ISSUE THREAD

**Issue by meltingsun** [CalaMariGold/Rebirth-Of-The-Night#158]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
The airship mod is not working? it corrupted ALL of our chests (normal+nether chests) that we just finished placing on there.
any idea how to get back the data of the items in the chest?

**To Reproduce**
not reproducable
**Crash Log**
Click "Get Link" from the crash and paste it here. Or post the log if it's a server.
https://paste.dimdev.org/asuyogotuw.mccrash

**Info (please complete the following information):**
 - Modpack Version: 
 - Server or Singleplayer:
 - Version the world was created on:

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by CalaMariGold** [comment]
Seems to be a common occurrence. We may remove DaVinci's Vessels soon in this case.

**Comment by kil0byt3** [comment]
Duplicate of https://github.com/CalaMariGold/Rebirth-Of-The-Night/issues/161 will likely remove DaVinci's
