### ISSUE TITLE
[BUG] Davinci's Vessel Destroyed upon Mounting Ship

### ISSUE THREAD

**Issue by Niner93R** [CalaMariGold/Rebirth-Of-The-Night#161]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
After using the ship's helm, assembling ship, then attempting to mount; about 90% of the blocks making up the ship vanished (no tile or block drops) leaving all players and animals on board intact. Any storage blocks, furnaces/kilns, etc were also destroyed, along with any items inside them.

**To Reproduce**
1. Use ship helm
2. Assemble ship
3. Attempt to mount

**Expected behavior**
Majority of ship blocks will vanish without drops, leaving entities intact.

**Screenshots**
[Aftermath](https://i.imgur.com/3RXDaZd.png)

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Server
 - Version the world was created on: 2.76.2

**Additional context**
The ship was drivable multiple times before, only difference this time being that passenger seats and animal crates from Davinci's vessels were added onto the ship.
Other differences include a named animalia peacock was standing in a crate, a 2nd player was standing on the deck on top of a passenger seat, and a refractory kiln sitting under the deck.

**Comment by kil0byt3** [comment]
Seems to be a common occurrence. We may remove DaVinci's Vessels soon in this case.
