### ISSUE TITLE
[BUG] UI System - responsive

### ISSUE THREAD

**Issue by Hydrocas** [CalaMariGold/Rebirth-Of-The-Night#162]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
I Have a massive offset on all the interface system. My cursor is affected by this offset as well. The bug persists in fullscreen mode and window mode. By the way, my monitor is a 27-inch screen and my resolution is 2560/1440. I already tested to configure a 1920/1080 resolution in my Minecraft launcher but with no success. :/

Sorry for my bad English. :)

**To Reproduce**
Have a 27-inch screen with a resolution of 2560/1440

**Expected behavior**
A massive offset on all the UI system

**Screenshots**
![bugUI](https://user-images.githubusercontent.com/45299492/77580040-98e10b80-6edb-11ea-848a-d6c6a63cd5d1.PNG)

**Info (please complete the following information):**
 - Modpack Version: 2.77
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by CalaMariGold** [comment]
Don't think this is anything on our end. Either a Minecraft issue or you just need to mess with the settings a little.
