### ISSUE TITLE
[BUG] FYI  Spawn.Json default values create heavy load per player

### ISSUE THREAD

**Issue by mactso** [CalaMariGold/Rebirth-Of-The-Night#164]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Wide use of "perplayer=true" instead of "perchunk=true" in spawn.json will cause escalating performance issues as the number of players running the mod pack increases.

**To Reproduce**
Start server
Set the nether, beneath, mythril, full suit armor achievements.
Have 1 player at a time login and observe CPU load rises.
On fairly powerful server ("Gold" at serverminer supposed to run 60 players) even mining gets difficult at three players with these achievements completed.

**Expected behavior**
Stuttery mob movement.   Difficulty mining as blocks fail to mine.
Very large numbers of mobs spawned when multiple players are close together.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: Rebirth of the Night-2.76.2.zip
 - Server or Singleplayer: Server
 - Version the world was created on:
Survival

**Additional context**
**FIX:** 
*** Simple:** 
Backup Spawn.json, then change all occurrences of "perplayer=true" to "perchunk=true"

*** Advanced:**
Modify a **few** *select* mobs (such as "hungryzombie") back to "perplayer=true".  This will allow some scaling but won't overwhelm the server with hundreds of mob spawns.

I recommend this be integrated into the modpack but in the advanced form where some mobs scale but most use standard minecraft mob cap behavior.

Hope this helps!  Made a huge difference on our server.

Mactso & Lupicus
Mods: Harder Branch Mining, Nasty Mobs, Enameled Armor.

**Comment by mactso** [comment]
Note- it appears one of the developers has seen my post about this on Reddit and responded.

**Comment by kil0byt3** [comment]
Hey Mactso & Lupicus - thanks for this, by the way. We're implementing a modified version of this into 2.77. I've worked with some community servers and saw big improvements. Thanks for the lead!
