### ISSUE TITLE
[BUG] Stray spawns are too low after unlocking beneath/mythril/nether/diamond gamestages

### ISSUE THREAD

**Issue by Eksekk** [CalaMariGold/Rebirth-Of-The-Night#166]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Before it, I could see strays spawn in expected quantity (about 30-40 per night?). After, it is good if I see a single stray **during entire night.**

**To Reproduce**
Compare nights in cold biomes before and after these gamestages.

**Expected behavior**
Stray spawns are more consistent.

**Screenshots**
N/A

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.76.2

**Additional context**
I've looked at the config files and found that monsters are assigned weights, which might be an issue once more monsters are able to spawn and stray spawn weight is smaller and smaller percentage of total sum.

I suppose the same also happens with husks.

**Comment by CalaMariGold** [comment]
That's mostly intended. As you progress, vanilla and less difficult mobs spawn less and less, since they are replaced by harder mobs. Not sure why you need strays to spawn anyway.

**Comment by Eksekk** [comment]
I understand mob progression, but strays are required because they drop ring of overclocking, which is not only a very useful bauble by itself, but also ingredient for ankh charm.

Maybe make it also drop from frostbounds (overworld)/wights (aether)? That would make sense, since they both use slowness extensively, while being available mid-to-late game.
