### ISSUE TITLE
[BUG] DaVinci's Vessels ship bug

### ISSUE THREAD

**Issue by Zxevi** [CalaMariGold/Rebirth-Of-The-Night#169]
**Describe the bug**
When creating a large ship with DaVinci's Vessels cause some of the ship to disappear and block to no longer drop blocks

**To Reproduce**

Build a massive ship around 1000 blocks and assemble
**Expected behavior**
Giant ship to assemble and work

Edit: apparently it is something to do with modded blocks that do not interact with davinci’s vessels properly and causes the ship to not form correctly
 
SOLUTION:
/gamerule doTileDrops true

**Comment by kil0byt3** [comment]
This mod is buggy and there's not a lot we can do especially with modded blocks. Working on a replacement for the future potentially.
