### ISSUE TITLE
[CRASH] PotionCore Potentially Causing Server Crashes

### ISSUE THREAD

**Issue by GunnerTardis** [CalaMariGold/Rebirth-Of-The-Night#173]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
Server starts normally but as soon as the player joins it crashes within a second and the server stops.

**To Reproduce**
Steps to reproduce the behavior: Login to the server and it will immediately crash when spawning in.

**Crash Log**
(https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4400800/crash-2020-03-30_04.29.59-server.txt)

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Server
 - Version the world was created on: 2.76.2

**Additional context**
Reading the crash logs it looks like its PotionCore causing the crash. Would love more insight on the issue I'd like to save my server :(

**Comment by GunnerTardis** [comment]
I actually was able to solve the issue and fix the crashing!

For anyone who actually has this same issue this is how to fix it:
Identify the player who is under any of the effects used by PotionCore(In my instance, I was getting attacked by a spider that put an effect on my character added by the mod itself)

Go into the server console or have an admin kill your character as soon as you join the server to cleanse the effect. This should solve the crashing!

**Comment by CalaMariGold** [comment]
@SandwichHorror didn't you fix this a few patches ago?

**Comment by SandwichHorror** [comment]
This shouldn't even be possible in 2.76.2, as Magic Shielding was removed from the list of potential witch buffs in 2.76.1 or earlier. Let us know if it happens again and give extra details about how exactly the mob got that buff.
