### ISSUE TITLE
[CRASH] Can't open the game, not sure if the reason is from Good Music or Nvidia optimization

### ISSUE THREAD

**Issue by NimzAgi** [CalaMariGold/Rebirth-Of-The-Night#174]
Kinda new on this ntgl

**Describe the crash**
its more of a can't open the game crash, so just trying to open isn't working for me

**To Reproduce**
Steps to reproduce the behavior: So, worked when i didn't put the files for the good music, but when i did(and also used the guide to upradge fps) it stopped launching the game, gets ready and then, crashs

**Crash Log**
[crash-2020-03-30_11.02.22-client.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4403389/crash-2020-03-30_11.02.22-client.txt)

**Additional context**
It had worked more than perfectly before, i played without the correct optimization and music and it worked fine, did have optifinte, but still were some fps downfalls and spikes, i have fallen in love with this modpack and a friend of mine wich i was playing with had no issues and told that i should enhance my experience with the good music, i really wanna use the good music, thx lov ya all

**Comment by CalaMariGold** [comment]
It's because of the custom music. Follow the wiki exactly. If it still crashes, I heard it might be busy you need Java 8 instead of the latest. I haven't tested it though and have been fine with the latest Java.
