### ISSUE TITLE
[BUG] No Electrum Nugget Recepie

### ISSUE THREAD

**Issue by Charmsnare** [CalaMariGold/Rebirth-Of-The-Night#176]
**Describe the bug**
You cannot craft Electrum Nuggets nor there is any other way to get them as far as I know.

**To Reproduce**
Try to do it.

**Expected behavior**
That you get Nuggets by putting the Ingots in the crafting Field/Bench

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.76.1

**Comment by CalaMariGold** [comment]
Fixed in 2.77
