### ISSUE TITLE
[BUG] No Crafting Recepie for Ankh Charm

### ISSUE THREAD

**Issue by Charmsnare** [CalaMariGold/Rebirth-Of-The-Night#177]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
No Crafting Recepie for Ankh Charm

**Expected behavior**

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.76.1

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by CalaMariGold** [comment]
Confirming with @Kompreya that this is fixed. @Kompreya update this issue if you fixed it.

**Comment by Kompreya** [comment]
Several baubles have had their recipes reworked in 2.77, including the Ankh charm. Check for its recipe when the update goes live =3
