### ISSUE TITLE
[BUG] Quark Elytra Dyeing not Working as Intended

### ISSUE THREAD

**Issue by MerchantNPC** [CalaMariGold/Rebirth-Of-The-Night#178]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
When dyeing an elytra (whether it be with dyes or the elytra cloning feature) they appear as they should in item form and when worn (but not in flight). When flying, the color reverts to un-dyed.

**To Reproduce**
1. Dye elytra
2. Wear
3. Fly

**Expected behavior**
In flight elytras should retain their color.

**Screenshots**
[What SHOULD happen](https://i.imgur.com/wxCdcsF.png)
[RotN (On Ground)](https://i.imgur.com/BXsMVC9.png)
[RotN (In Flight)](https://i.imgur.com/GAtisLh.png)

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Both
 - Version the world was created on: 2.76.2

**Additional context**
Possibly any other mod that does stuff to elytras could be causing the issue, if that edit affects elytras while in flight. Maybe.

**Comment by CalaMariGold** [comment]
I found this in the Quark config.

```
# Should the crafted Elytra be dyed black? (only works if Dyed Elytras from Vanity is loaded)
        B:"Dye Elytra Black"=true
```

No idea what Vanity is, assume it a mod but I can't find it.

**Comment by MerchantNPC** [comment]
> No idea what Vanity is, assume it a mod but I can't find it.

Vanity is a quark module.
Part of that module is allowing elytras to be dyed.

**Comment by CalaMariGold** [comment]
`    B:vanity=true
`
Not sure. Post an issue on Quark's GitHub page.
