### ISSUE TITLE
[BUG] Ender Spectacles have no crafting recipe

### ISSUE THREAD

**Issue by Eksekk** [CalaMariGold/Rebirth-Of-The-Night#181]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
In title.

**To Reproduce**
Look them up in JEI.

**Expected behavior**
They have crafting recipe.

**Screenshots**
N/A

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.76.2

**Additional context**
N/A

**Comment by SandwichHorror** [comment]
Intended. In a future update, perhaps 2.78, they will no longer appear on the advancement tab. It won't be in 2.77 because we will make an entire custom tab for machines and similar multiblocks.

**Comment by Eksekk** [comment]
Can I ask why were they removed? Also, it would be nice to put this in their JEI information tab.
