### ISSUE TITLE
[BUG] Getting teleported outside of the map

### ISSUE THREAD

**Issue by LovelyTm** [CalaMariGold/Rebirth-Of-The-Night#185]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
I walked and was teleported to a the coordinate y-191 (outside of the map) and was killed.

**To Reproduce**
No fucking clue.

**Expected behavior**
To die? No idea. I was waiting for the server to refresh to see if I was just out of sync or something. In the video I was frantically typing "What" over and over as I suspected that my friend was just messing with me and that he would teleport me back out. But he had no idea idea what happened until I showed him the video.

**Screenshots**
https://www.youtube.com/watch?v=eJFsowxBt-I&

**Info (please complete the following information):**
Version 2.76
Server
World version 2.76

**Comment by Kompreya** [comment]
Do you have server logs? Anything that we can look at with a time stamp? Not sure if this is a pack issue or a server issue.

**Comment by CalaMariGold** [comment]
Yeahhhhhhh I'm gonna go out on a whim here and say someone in the server pranked you. If you're not gonna provide any sort of log, then I'm gonna close this issue
