### ISSUE TITLE
[BUG] Dungeon Tactics silver ore doesn't smelt in blast furnace

### ISSUE THREAD

**Issue by UDK450** [CalaMariGold/Rebirth-Of-The-Night#187]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Dungeon tactics silver ore does not have a Smelting recipe for the Blast Furnace.

**To Reproduce**
1. Obtain Dungeon Tactics silver ore
2. Place ore with fuel in Blast Furnace
3. No smelted ore :(

**Expected behavior**
Dungeon tactics silver ore should smelt into the respective metal when smelted in Blast Furnace.

**Screenshots**
![image](https://user-images.githubusercontent.com/15207201/78419604-43140e00-7615-11ea-8531-3a1dde7c068e.png)

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Server and Singleplayer
 - Version the world was created on: 2.76.2

**Additional context**
I first encountered this with silver ore that I at some point obtained, perhaps while in a stronghold in the Beneath (on that part, I am not quite sure). We tried throwing it into our auto smelter, only to realize that it got hung up on the silver ore in the blast furnace. Looking at the recipes involving it, we could see that it did not have a recipe implementing the use of the Blast Furnace to turn it into silver ingot. 

In fact, the fact that silver_ore exists in dungeon tactics is odd, as it doesn't seem like diamond, iron, or other ore even exists as an option to give myself with the give command.

**Comment by CalaMariGold** [comment]
Intended (mostly). You shouldn't be able to get DT silver anymore in 2.77.
