### ISSUE TITLE
[BUG] Natural Lava + Water does not turn into obsidian

### ISSUE THREAD

**Issue by MegaGlub** [CalaMariGold/Rebirth-Of-The-Night#192]
Pretty simple. In the 2.77 beta, water source blocks and lava source block that naturally occur adjacent to each other do not form obsidian.
![image](https://user-images.githubusercontent.com/45982508/78465900-85425b80-76b8-11ea-9288-fdfd6c6c0a55.png)

**Comment by CalaMariGold** [comment]
I think this has always been a thing. A lot of times, during world generation, water and lava don't flow when they're supposed to. Not much we can do about this.
