### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CynicalButthole** [CalaMariGold/Rebirth-Of-The-Night#193]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
No ding sound upon start up.

**To Reproduce**
Start up lol

**Expected behavior**
Ding

**Screenshots**
???

**Info (please complete the following information):**
 - Modpack Version: 2.77Beta
 - Server or Singleplayer:N/A
 - Version the world was created on:2.77Beta

**Additional context**
Want ding

**Comment by CalaMariGold** [comment]
Ding
