### ISSUE TITLE
[CRASH] Random Crash when near custom structures or custom villages

### ISSUE THREAD

**Issue by WZT006** [CalaMariGold/Rebirth-Of-The-Night#194]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
Server randomly crashes when a player is near a custom structure or a village with a village lord

**To Reproduce**
Seems to happen when a player stays and interact enough with the village.

**Crash Log**
[Server Crash Report Ver 2.77 pre-Release.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4434387/Server.Crash.Report.Ver.2.77.pre-Release.txt)

**Info (please complete the following information):**
 - Modpack Version: 2.77 Pre-Release
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77 Pre-Release (with orespawn3.json config edited)

**Additional context**
Admin was on grassland biome inside the village, player was heading towards an abandoned hut custom structure in a steppe hill.

**Comment by Foreck1** [comment]
Related to [https://github.com/crazysnailboy/VillagerTrades/issues/32](url). This mod has been removed in upcoming version and we'll try to add it again at a later date.
