### ISSUE TITLE
[CRASH] Upon opening furnace

### ISSUE THREAD

**Issue by Niner93R** [CalaMariGold/Rebirth-Of-The-Night#195]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
Attempted to open a furnace from the top side, instant crash.

**To Reproduce**
Open a furnace from the top?

**Crash Log**
[crash-2020-04-05_12.56.05-client.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4434559/crash-2020-04-05_12.56.05-client.txt)

**Info (please complete the following information):**
 - Modpack Version: 2.77 Pre-release
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77 Pre-release

**Comment by CalaMariGold** [comment]
Any more info? What was in the furnace? Anything to do with Arcane Archives around you?

**Comment by Niner93R** [comment]
Nothing in the furnace. No arcane archives nearby let alone crafted

**Comment by kil0byt3** [comment]
Interesting. Which shaders were you using

**Comment by Niner93R** [comment]
@kil0byt3 It doesn't matter what shaders are used, and it seems the crash is hit or miss. It's weird.

**Comment by democat3457** [comment]
Did you have a radiant tank open in jei? It appears the crash happened when it was trying to render the Radiant Tank as an Item/Ingredient in JEI, even though the screen render was a furnace.

**Comment by democat3457** [comment]
Duplicate of #389
