### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by matthew24fan** [CalaMariGold/Rebirth-Of-The-Night#196]
https://paste.dimdev.org/adixeyenor.mccrash

**Comment by Foreck1** [comment]
Please follow the template when reporting bugs. Did this happen when updating to the newest version? Was the Nether world a new one or an old one?

**Comment by matthew24fan** [comment]
This happened on startup i wasnt even able to play the game. It loaded all
the mods and said netherEX and LibraryEX caused the crash.

**Comment by SandwichHorror** [comment]
Unfortunately that actually answered none of the questions he asked.

**Comment by matthew24fan** [comment]
Im saying the nether world hadnt been created yet because i wasnt able to
play the modpack and this was the newest version.
