### ISSUE TITLE
[BUG] Cursor Disappearing

### ISSUE THREAD

**Issue by CynicalButthole** [CalaMariGold/Rebirth-Of-The-Night#197]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Cursor will disappear, still usable but not visible.

**To Reproduce**
Steps to reproduce the behavior: Not totally sure, but happens when leaving the inventory from time to time.

**Expected behavior**
Cursor no go bye :(
![2020-04-05_22 06 31](https://user-images.githubusercontent.com/32186300/78524802-f00f9780-7789-11ea-868b-4c99dfaa4956.png)

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.77 Pre-release
 - Server or Singleplayer: Both
 - Version the world was created on: 2.77-Pre-release v2

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by CalaMariGold** [comment]
I disabled dynamic cursor. Let me know if this is fixed in the full release.

**Comment by CalaMariGold** [comment]
Fixed
