### ISSUE TITLE
[SUGGESTION] Name Pain

### ISSUE THREAD

**Issue by naqaden** [CalaMariGold/Rebirth-Of-The-Night#198]
I hope this is the right place for mod suggestions, if you're taking them.

[Name Pain](https://www.curseforge.com/minecraft/mc-mods/name-pain) is a light QoL client-side mod primarily for visualizing the health of friends and pets via nameplate color, but this pack already has Neat. What it does well as a companion to Neat is allow the hiding of vanilla nameplates via RGBA configs, eliminating redundancy. If both styles of nameplates are desired, Name Pain could just be used to fit a cosmetic theme.

**Comment by CalaMariGold** [comment]
Player name plates are disabled. Still, we'll look at this for 2.78, because disabling vanilla name plates for mobs would be great, since we have Neat as you said.

**Comment by naqaden** [comment]
Great. I'm open to feedback to make it work.

**Comment by kil0byt3** [comment]
Thanks for your suggestion!

**Comment by naqaden** [comment]
I see RotN Tweaker is going to replace this. It's probably for the best since this does more than RotN needs. I just wanted to see if there were any issues that weren't reported to Name Pain, and found #508 and #521. If I'm missing any others, please let me know. Thanks!
