### ISSUE TITLE
[CRASH] Server crashed on start up

### ISSUE THREAD

**Issue by OneBakaBoi** [CalaMariGold/Rebirth-Of-The-Night#199]
Downloaded the PRE-RELEASED 2.77 server pack. Uploaded to my server (using server.pro to host my server)
During the startup the server crashes out. Constantly getting the same crash report.
Can't even join the server since it unable to start.

Reproduction:
Uploaded the zip file to my server, unzipped it, started up the server, then crashed after a little bit

Log:
https://pastebin.com/Z2xPz6Ab

Info (please complete the following information):**
 - Modpack Version: 2.77 (pre-release)
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77

Additional Context:
This method of installing the modpack to the server worked perfectly with the 2.76.2 version of the modpack

**Comment by CalaMariGold** [comment]
Remove the mod Non Update and let me know if that fixes it

**Comment by OneBakaBoi** [comment]
That worked! Love ya!
