### ISSUE TITLE
[BUG] Iron Sledgehammer doesn't work

### ISSUE THREAD

**Issue by Eksekk** [CalaMariGold/Rebirth-Of-The-Night#201]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Iron sledgehammer doesn't work, Steve swings it as if "using" but no progress appears on item. Exhaustion (hunger) level also doesn't change.

**To Reproduce**
Use iron sledgehammer on anything.

**Expected behavior**
It works.

**Screenshots**
N/A

**Info (please complete the following information):**
 - Modpack Version: 2.77 prerelease
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77 prerelease

**Additional context**
N/A

**Comment by Foreck1** [comment]
Fixed in next version
