### ISSUE TITLE
[BUG] Repairing bronze equipment is inefficient

### ISSUE THREAD

**Issue by Eksekk** [CalaMariGold/Rebirth-Of-The-Night#202]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Basically, every anvil repair adds only 50 durability (looked up in scripts) instead of 25% of item's max durability. Even worse, you can use only 1 ingot at a time, which destroys your anvil MUCH more quicker. Also repair always takes 1 exp level, no matter how many times item was enchanted in anvil previously (haven't checked if "too expensive" still applies).

**To Reproduce**
Damage any bronze equipment/tool and try to repair it.

**Expected behavior**
Repair worked as if with iron, diamond etc. items.

**Screenshots**
N/A

**Info (please complete the following information):**
 - Modpack Version: 2.77 prerelease
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77 prerelease

**Additional context**
This bug also was in 2.76.2.

**Comment by CalaMariGold** [comment]
We'll see what we can do. It won't be for 2.77 though most likely.

**Comment by CalaMariGold** [comment]
We did what we could for 2.77
