### ISSUE TITLE
[BUG] Spiders attack through blocks

### ISSUE THREAD

**Issue by Eksekk** [CalaMariGold/Rebirth-Of-The-Night#204]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
In title. Most recent example was pale spider 1-2 blocks below me, I was standing above on dirt and got attacked constantly.

**To Reproduce**
Find or make a platform with spider below you, then move around.

**Expected behavior**
Spiders don't attack through blocks.

**Screenshots**
N/A

**Info (please complete the following information):**
 - Modpack Version: 2.77 prerelease
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77 prerelease

**Additional context**
N/A

**Comment by ItzRaiderr** [comment]
Yea, this happened to me too you know. I got poisoned by cave spiders, they were tiny and attacked me through blocks (wooden plank)

**Comment by CalaMariGold** [comment]
Mod bug. Nothing we can do about it, especially since we don't know what mod causes it.
