### ISSUE TITLE
[BUG]Can't create pulp on granite anvil

### ISSUE THREAD

**Issue by quaid111** [CalaMariGold/Rebirth-Of-The-Night#206]
**Describe the bug**
JEI states that you can break down wood blocks on a granite anvil with a hammer into pulp. I've tried almost every hammer with no results.

**To Reproduce**
Steps to reproduce the behavior: Put Wood Block on granite anvil and right click with hammer

**Expected behavior**
right clicking would break down wood block into 8 pulp after a certain number of swings.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/20942395/78720980-4ac10480-78ec-11ea-9f68-f97edcf92a02.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77 Pre-Release
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77 Pre-Release

**Additional context**
Right clicking the wood with any kind of hammer does nothing. Using a pickaxe to create wood chips works fine, however.

**Comment by Foreck1** [comment]
This has been fixed in next version.
