### ISSUE TITLE
No Pit Kiln! [BUG]

### ISSUE THREAD

**Issue by ThetasFiasco** [CalaMariGold/Rebirth-Of-The-Night#208]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
As it stands, there's no way to get wood tar in 2.77 (to my knowledge). The Pit Kiln required isn't enabled in the pack, for whatever reason, and the method of Pit Burning seems to be broken as well.
**To Reproduce**
Try Pit Burning.
**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.77 pre-release
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77 pre-release

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by Foreck1** [comment]
Pit kiln is completely disabled (stone kiln is easier), therefore you must use pit burning for wood tar. Wood tar is working perfectly fine and can be collected the intended way. If you have any more info please let us know.
![image](https://user-images.githubusercontent.com/47757429/78846206-02cbdb80-79d9-11ea-8189-1977b5225325.png)
