### ISSUE TITLE
Baa, The Friendly Grove Sprite is offline, causing problems with your Discord. 

### ISSUE THREAD

**Issue by Gunner76th** [CalaMariGold/Rebirth-Of-The-Night#209]
This is to inform you that as of 07March2020 at around 1730 EDT your welcome bot Baa, The Friendly Grove Sprite went offline and stopped welcoming individuals onto the Discord server. As a result, no new visitors since that time have been able to speak and request assistance. Please have the individual(s) who are able to manage the bot address this issue as soon as possible. 

I am a moderator for Dreams Discord for the Roguelike Adventures and Dungeons modpack, and we have people coming to us for assistance because your Discord is currently inaccessible.

**Comment by Kompreya** [comment]
Dyno is currently offline. We just have to wait til the Dyno devs resolve the issue. We've temporarily allowed members to join our regular channels without the bot until it's resolved.

https://twitter.com/DynoDiscord/status/1247666259996446720?s=20

**Comment by Gunner76th** [comment]
And yes, this was supposed to be 07April2020 not March lol. Sorry for that mistype. 

Thank you for addressing this.
