### ISSUE TITLE
[CRASH] Forgelin Server crash on startup

### ISSUE THREAD

**Issue by unicornbloods** [CalaMariGold/Rebirth-Of-The-Night#210]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
This crash occurs when starting my server with ROTN 2.76

**To Reproduce**
Steps to reproduce the behavior: Start server.

**Crash Log**
Click "Get Link" from the crash and paste it here. Or post the log if it's a server.

 Hastebin link: https://paste.dimdev.org/ucuhujolil.rb

**Info (please complete the following information):**
 - Modpack Version: 2.76
 - Server or Singleplayer: Server
 - Version the world was created on: 2.76

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

The server is "self hosted" (My friend hosts it not I but I do all the install stuff).

**Comment by kil0byt3** [comment]
Should be solved with 2.77, reopen if not
