### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by xGingerr** [CalaMariGold/Rebirth-Of-The-Night#211]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
I've come across a woodland mansion and it crashed my game. Now it is unjoinable.
**To Reproduce**
Walk next to a woodland mansion.
**Crash Log**
https://paste.dimdev.org/zoyolereye.mccrash

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Singleplayer with LAN
 - Version the world was created on: forge-14.23.5.2847

**Additional context**
NONE

**Comment by kil0byt3** [comment]
That unfortunately looks like a corrupted chunk. Not caused by the modpack - might be from exiting the game before it saved, or a power outage, etc. You'll have to load a backup (if you have one), or try to fix the chunk corruption. Here's a thread/tool I found that might help.
