### ISSUE TITLE
[CRASH] Possible issue with villages

### ISSUE THREAD

**Issue by edenhack** [CalaMariGold/Rebirth-Of-The-Night#212]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
User Slavvy McStabby was flying in a creative world when his client crashed.

**To Reproduce**
From report its possible each village might cause this crash.

**Crash Log**
Click "Get Link" from the crash and paste it here. Or post the log if it's a server.

**Info (please complete the following information):**
 - Modpack Version: 2.77
 - Server or Singleplayer: Singleplayer Creative
 - Version the world was created on: 2.77

**Additional context**
User Slavvy McStabby does not have a github, I will relay any information to him but this IS his reported crash.
Since he sent me the crash report I've posted it since I had no link. I hope this is ok.
[crash-2020-04-08_22.30.47-server.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4454229/crash-2020-04-08_22.30.47-server.txt)

**Comment by CalaMariGold** [comment]
Fixed
