### ISSUE TITLE
[CRASH] Server crash on start up.

### ISSUE THREAD

**Issue by Acoustickid** [CalaMariGold/Rebirth-Of-The-Night#214]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
The crash occurs when starting up the server.

**To Reproduce**
Start the server with an executable file.  Im using linux so in my case im using a sh script.

**Crash Log**
https://pastebin.com/LCtz19xP

**Info (please complete the following information):**
 - Modpack Version: 2.77
 - Server or Singleplayer: Server
 - Version the world was created on: 2.76

**Additional context**
The server is running on Centos 8 with the latest java version.

**Comment by CalaMariGold** [comment]
Reinstall the pack. If it still doesnt work, then it's some issue with linux
