### ISSUE TITLE
[CRASH] village crash report

### ISSUE THREAD

**Issue by Dcrypt** [CalaMariGold/Rebirth-Of-The-Night#216]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
Crash while in village. Seems like getting near village will cause the crash

**To Reproduce**
Created another world using latest version with same seed and visit the village.

**Crash Log**
https://pastebin.com/GcJ1Ktdi

**Info (please complete the following information):**
 - Modpack Version: 2.76
 - Server or Singleplayer: singleplayer
 - Version the world was created on: 2.77

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by CalaMariGold** [comment]
Fixed
