### ISSUE TITLE
[BUG] True Lights Edge bugged

### ISSUE THREAD

**Issue by Charmsnare** [CalaMariGold/Rebirth-Of-The-Night#218]
**Describe the bug**
The True Lights Edge got no enchants when u craft it. (also no living enchant)
Also the games crashes EVERY time when u want to put it into the true enchant table.

**To Reproduce**
Craft it and try it with the true enchant table

**Expected behavior**
that the blade got enchants already when u craft it and that the game does not crash when u want to enchant it with the true enchant table

**Info (please complete the following information):**
 - Modpack Version: 2.77
 - Server or Singleplayer: single
 - Version the world was created on: 2.76.1

**Comment by Charmsnare** [comment]
Same for the True Darks Edge. It has 3 Enchants when u craft it but no living enchant.
the game also crashes EVERY time when u want to but a crafted True Darks edge in the True enchant table.  There is no Problem when u drag the true Darks edge out of the creative menu

**Comment by CalaMariGold** [comment]
You have to create a new world
