### ISSUE TITLE
[CRASH] Crash near Village with Lord

### ISSUE THREAD

**Issue by WZT006** [CalaMariGold/Rebirth-Of-The-Night#219]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
Heading towards a village with village lord

**To Reproduce**
Small Renderdistance while going towards a village with a lord

**Crash Log**
[crash-2020-04-09_21.07.23-server.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4456321/crash-2020-04-09_21.07.23-server.txt)

**Info (please complete the following information):**
 - Modpack Version:  2.77
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77

**Additional context**

**Comment by Foreck1** [comment]
We'll release a hotfix today that hopefully will fix this.
