### ISSUE TITLE
[BUG] Seasons don't seem to pass in the last update.

### ISSUE THREAD

**Issue by Insane96** [CalaMariGold/Rebirth-Of-The-Night#221]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
 Seasons don't seem to pass in the last update. I'm playing on a server updated to 2.77. Even changing the season manually with commands it goes back to late winter. The server MOTD says Spring but it's actually winter when you join the server as crops supposed to grow in spring don't.
Even tried rebooting the server. Also when I change the season in-game the season clock blinks for a few seconds between winter and spring, but goes back to winter.

**To Reproduce**
Steps to reproduce the behavior: Update an old world to 2.77?

**Expected behavior**
Seasons to pass correctly

**Screenshots**
![2020-04-09_20 05 46](https://user-images.githubusercontent.com/7185104/78926626-aed6fa80-7a9d-11ea-9e44-897e0f9fdb24.png)
![2020-04-09_20 05 41](https://user-images.githubusercontent.com/7185104/78926628-af6f9100-7a9d-11ea-9640-58563cba7ab7.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77
 - Server or Singleplayer: Server
 - Version the world was created on: 2.76.2

**Comment by CalaMariGold** [comment]
Possibly because seasons don't progress when no one is online, but the days are
