### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by sayso9** [CalaMariGold/Rebirth-Of-The-Night#222]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
Seemingly random crash a couple of minutes after joining the server. Crash has been consistent across 3 attempts to restart the server.

**To Reproduce**
Steps to reproduce the behavior: Joining the server is the only apparent step

**Crash Log**
Posted the log

**Info (please complete the following information):**
 - Modpack Version: 2.77
 - Server or Singleplayer: Server (Akliz, copied files over from 2.77 server files)
 - Version the world was created on: 2.77

**Additional context**
Saw a lot of cascading world gen issues in the server log, might be relevant idk
[crash-2020-04-09_18.35.02-server.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4458087/crash-2020-04-09_18.35.02-server.txt)

**Comment by CalaMariGold** [comment]
When did you install the server pack? Does it have vtt.cfg and vtt folder in it?

**Comment by sayso9** [comment]
I installed the server pack an hour ago, I'll check for those files

**Comment by sayso9** [comment]
it has vtt folder but no vtt.cfg

**Comment by CalaMariGold** [comment]
Delete that folder and let me know if it fixes. Both client and server

**Comment by sayso9** [comment]
Not sure if it fixed, but it has been running for about 5 minutes no crash. If it crashes again I will reopen with the new crash report
