### ISSUE TITLE
[CRASH]When trying to interract with village lord  (toroquest)

### ISSUE THREAD

**Issue by ItzRaiderr** [CalaMariGold/Rebirth-Of-The-Night#223]
**Describe the crash**
The game displays error message "Toroquest ran into a problem" when I try to interact with the village lord. 

**To Reproduce**
Try to interact with the village lord.

**Crash Log**
[https://pastebin.com/69Ks2hnw](url)

**Info (please complete the following information):**
 - Modpack Version: v2.77 (latest)
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: v2.77 pre-release

**Additional context**
Updating to newer version? :3

**Comment by democat3457** [comment]
pastebin link has expired 😞

**Comment by democat3457** [comment]
Not enough information (especially since its an old version, a toro update is coming soon, and the pastebin is expired)
