### ISSUE TITLE
Chopping block not craftable with Bronze Axe[BUG]

### ISSUE THREAD

**Issue by CynicalButthole** [CalaMariGold/Rebirth-Of-The-Night#224]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
You cannot create a chopping block with any wood and a bronze axe.

**To Reproduce**
You know

**Expected behavior**
Making a chopping block

**Screenshots**
Included ![2020-04-09_16 17 22](https://user-images.githubusercontent.com/32186300/78948626-dcac4700-7a7d-11ea-80ba-8d9a58d5e05a.png)
![2020-04-09_16 17 34](https://user-images.githubusercontent.com/32186300/78948627-dd44dd80-7a7d-11ea-997a-df1ad4cea739.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77 Official Release
 - Server or Singleplayer: Both
 - Version the world was created on: 2.77PR, converted to 2.77OR

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by cutcat101** [comment]
Should be fixed in next update
Thanks for the heads up
