### ISSUE TITLE
[BUG] Enchanted Pickaxe healing Slider Boss

### ISSUE THREAD

**Issue by Niner93R** [CalaMariGold/Rebirth-Of-The-Night#226]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
When fighting slider it appears certain enchanted picks heal it by a large margin

**To Reproduce**
Attack slider with a pick possibly similar to below

**Expected behavior**
Slider gets hurt, not full healed.

**Screenshots**
![image](https://user-images.githubusercontent.com/49265152/78952668-982ba600-7a93-11ea-812d-c8bb5c8b527b.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77 Hotfix
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77 Offical Release

**Additional context**
N/A

**Comment by CalaMariGold** [comment]
Don't use an enchanted pick on the boss then
