### ISSUE TITLE
[CRASH] Server Crash on Join

### ISSUE THREAD

**Issue by WZT006** [CalaMariGold/Rebirth-Of-The-Night#228]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
Joining from a world 2.77 pre-hotfix to 2.77 post-hotfix crashes

**To Reproduce**
update server to hotfix without new world

**Crash Log**
[crash-2020-04-10_13.42.40-server.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4460068/crash-2020-04-10_13.42.40-server.txt)

**Info (please complete the following information):**
 - Modpack Version: 2.77 post-hotfix
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77 pre-hotfix

**Additional context**
Join was inside or near a village

**Comment by kil0byt3** [comment]
Village bug, should be fixed in 2.77.1
