### ISSUE TITLE
[BUG] Rats are untameable with animania cheese

### ISSUE THREAD

**Issue by Mrmang0** [CalaMariGold/Rebirth-Of-The-Night#229]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
when i try to tame a rat with animania cheese rat is untameble 

**To Reproduce**
throw animania cheese to rat (i tried 32 pieces)

**Expected behavior**
rat should be tamed

**Info (please complete the following information):**
 - 2.72v: 
 - Server:
 - 2.72:

**Comment by SandwichHorror** [comment]
This is a known bug, but for know we have the workaround where you can turn any cheese into Cheese Chunks, which DO tame rats. You get 4 chunks from each piece of cheese, too, so it's easier.
It's been reported to the rats developer.
