### ISSUE TITLE
[BUG] Ferrous Knights bugged

### ISSUE THREAD

**Issue by varvolgyibeni** [CalaMariGold/Rebirth-Of-The-Night#23]
Ferrous knights barely attack me, and generally stand in one place, their heads always looking at me ignoring the body's rotation. when i get near them i get 1 heart of damage dealt constantly, yet they rarely attack.

**Comment by CalaMariGold** [comment]
Issue for the Mowzie's Mobs developer.

**Comment by SandwichHorror** [comment]
fixed in 2.75

**Comment by SandwichHorror** [comment]
Was incompatibility with Epic Siege AI modification.
