### ISSUE TITLE
[CRASH] Random crash on server while i`m exploring

### ISSUE THREAD

**Issue by TheDuke92** [CalaMariGold/Rebirth-Of-The-Night#230]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
server crash while someone is exploring near a village
**To Reproduce**
exploring new chuncks

**Crash Log**
Click "Get Link" from the crash and paste it here. Or post the log if it's a server.
[
[crash-2020-04-10_22.24.50-server.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4463332/crash-2020-04-10_22.24.50-server.txt)
](url)
**Info (please complete the following information):**
 - Modpack Version: 2.77
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77

**Additional context**
I fixed the crash by removing the "Charm" mod

**Comment by kil0byt3** [comment]
Got it. Tracking this issue with villages as part of 2.77.1. Already fixed in dev. Thanks!
