### ISSUE TITLE
[BUG] When logging into a MP server during an invasion, you might get a different invasion than everyone else.

### ISSUE THREAD

**Issue by Niner93R** [CalaMariGold/Rebirth-Of-The-Night#231]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Upon logging into a server you might get a different invasion than those already logged on when it started.
i.e.; Jim and Jack got a Skeleton Invasion, Jerry logged on halfway through to get a Spider Invasion

**To Reproduce**
1. Stay off server until an invasion starts
2. Log in once it's already started

**Expected behavior**
Same invasion as everyone else already logged in is experiencing

**Info (please complete the following information):**
 - Modpack Version: 2.77 Hotfix 
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77 Offical Release

**Comment by kil0byt3** [comment]
This is actually working as intended/not fixable. Invasions are determined per player/game stage.
