### ISSUE TITLE
[CRASH] Division By Zero During Launch

### ISSUE THREAD

**Issue by skeletalsandwich** [CalaMariGold/Rebirth-Of-The-Night#233]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
A clear and concise description of what happened when you crash. Also, tell us if it continues to crash on world join or if it was a one time thing.

When launching the game on MultiMC, the game loads as normal until it looks like it tries to bake the model for BetterWithMods's Stone Mould, in which the window closes and it crashes. The error log mentions Java trying to divide by zero.
**To Reproduce**
1. Create an instance in MultiMC using the .zip file for Rebirth of the Night Version 2.7.7
2. Place Optifine (version 1.12.2_HD_U_F5) in the mods folder.
3. Change maximum memory allocation to 8096.
4. Launch game.
5. ???
6. Profit.

**Crash Log**
Click "Get Link" from the crash and paste it here. Or post the log if it's a server.

[crash-2020-04-10_17.27.37-client.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4463818/crash-2020-04-10_17.27.37-client.txt)

**Info (please complete the following information):**
 - Modpack Version: 2.7.7
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 1.12.2

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

This is on a Mac OS X El Capitan, if that helps. I didn't try to install music.

**Comment by CalaMariGold** [comment]
Don't know. Not on our end so try reinstall the modpack and trying other install methods
