### ISSUE TITLE
Refined Chain recipe still uses it original recipe [BUG]

### ISSUE THREAD

**Issue by DragonmasterDJ** [CalaMariGold/Rebirth-Of-The-Night#235]
**Describe the bug**
The Refined chain recipe doesn't have its original recipe removed

**To Reproduce**
(not needed)

**Expected behaviour**
The new recipe to be the only available recipe

**Screenshots**
![image](https://user-images.githubusercontent.com/29170640/79049244-c6f97600-7c65-11ea-9490-adb12b105133.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77

**Additional context**
none! Just happy to help if this is an intended bug

**Comment by Foreck1** [comment]
Thanks for reporting! I overlooked this one

**Comment by DragonmasterDJ** [comment]
No worries! Glad to help! ❤
