### ISSUE TITLE
[CRASH] Picking up certain items corrupts the player save

### ISSUE THREAD

**Issue by Dumbino** [CalaMariGold/Rebirth-Of-The-Night#236]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
My friend made a diamond reinforced longbow and immediately crashed off my server and couldn't get back on, he'd just join and be kicked off again. I cheated myself the materials just to reproduce it to see if that was the issue, the same thing happened to me. I was forced to use NBTExplorer just to let us get back on the server again and I had to delete the entry for the longbow from within.

The same thing also happened when I looted a "Coin cannon" from a Nether chest dungeon (those little pocket areas with a blaze spawner and 4 chests). There might be others that do this too, but these are the only two that I've found.

**To Reproduce**
Just craft/loot a diamond reinforced longbow or coin cannon ON A SERVER. Once it's in your inventory, you get kicked and can't log on again. It seems to crash single-player too, but only once (sometimes not at all) and it's a lot more lenient (until you drop it and pick it back up again one or a few times?).

**Crash Log**
SP world crash: https://pastebin.com/VGyCtBpf
Server world crash: https://pastebin.com/sRydR6uQ

**Info (please complete the following information):**
 - Modpack Version: 2.77
 - Server or Singleplayer: Both
 - Version the world was created on: 2.77

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by Dumbino** [comment]
I tested it more thoroughly, this happens with ANY ranged item that uses ammo, seemingly (javelins and throwing axes are fine, any sort of bow or crossbow is not) but it only SOMETIMES happens in single player? I tested it in one world creation and it was fine. Then the next SP world I made 5 minutes later, it'd crash as soon as I picked up a ranged weapon again.

I also remembered my friend being able to use a bow much earlier, somehow, but later on any sort of ranged weapon started crashing us again for some reason. I'm seriously weirded out by this and how it doesn't seem to be affecting anyone but us.

**Comment by kil0byt3** [comment]
This sounds like an issue with bow/crossbow Qualities. Could you try this in 2.77.1?

**Comment by Dumbino** [comment]
Okay, so I figured out what happened and it's actually a little embarrassing on my part. In short, **the new qualities you guys recently added aren't actually implemented, and at least one of them (the bow one(s)) crashes the game almost consistently.**

When I first saw in the changelog that you guys added new qualities, I was kind of excited to look at them. I'm by no means an expert with reading/doing mods but I have a basic understanding to see what things do, and I noticed there were two different folders in the quality tools config ("Qualities" and "Quailities"). The mod seems to only use Quailities, and all of the new ones you added are in Qualities, so I copied them over. I know it worked, because I wasn't seeing the new ones until after I did this, but apparently there's something it doesn't like about the bow ones.

So, I redid this and copied all the files from Qualities to Quailities back over EXCEPT the bow ones. Works like a charm and I have (almost) all the new quality modifiers without crashing. I suspect this will work on 2.77.1 too, but I'll keep this open until after I test it/in case you want to look at the results.

**Comment by kil0byt3** [comment]
Yeah, they're bugged/misspelled right now. Thanks for the details and the explanation. It was weird that it was just happening to you/your friend - I'll look into this

**Comment by Dumbino** [comment]
It's just as I suspected, even in 2.77.1 the server doesn't crash if I avoid copying over the list of the bow modifiers; all the others are fine. It should probably be noted that all the new qualities are still in the wrong folder regardless and don't get used unless they're in Quailities. Closing this now as it's more or less fixed.
