### ISSUE TITLE
Sledgehammers need full durability to craft cobblestone

### ISSUE THREAD

**Issue by CoolKiller32** [CalaMariGold/Rebirth-Of-The-Night#238]
You can only craft one cobblestone with a sledgehammer because only a full durability sledgehammer works for turning other cobblestones into regular cobblestone.

**Comment by kil0byt3** [comment]
Got it. The 2x2 recipe for regular cobblestone should still work. This is a recipe bug we’ll fix in 2.77.1.

**Comment by kil0byt3** [comment]
Fixed in 2.77.1
