### ISSUE TITLE
.bat edit

### ISSUE THREAD

**Issue by lawman-of-lawania** [CalaMariGold/Rebirth-Of-The-Night#239]
on the read me!!!.txt file step 3. for the issues of java it does not allow me to edit the .bat file.
secondly what does it mean by with a text

**Comment by lawman-of-lawania** [comment]
quick further explanation: it does not allow me change anything in properties or rename the files. as such I don't know how I am meant to do edits

**Comment by kil0byt3** [comment]
You edit the bat file using notepad. This is standard for an Minecraft server.
