### ISSUE TITLE
[BUG] No ores other than Copper and rarely coal spawns in Quartzite

### ISSUE THREAD

**Issue by Insane96** [CalaMariGold/Rebirth-Of-The-Night#240]
**Describe the bug**
Explored a whole quartzite cave and got tons of copper, little to none coal and 0 of any other materials.

**To Reproduce**
Find a Overgrown Cliff biome.
Descent into caves
Profit

**Expected behavior**
To find all the ores that you can normally find in any stone/biome

**Screenshots**
![image](https://user-images.githubusercontent.com/7185104/79098002-559eed80-7d61-11ea-8582-f9cff2150560.png)
![image](https://user-images.githubusercontent.com/7185104/79098060-6ea79e80-7d61-11ea-9df5-0b314f599c81.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77 (hotfix re-upload)
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77 (hotfix re-upload)

**Comment by CalaMariGold** [comment]
Issue in the pre-release. Make a new world
