### ISSUE TITLE
[CRASH] Crashes on Launch

### ISSUE THREAD

**Issue by banjojimserb** [CalaMariGold/Rebirth-Of-The-Night#243]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
When I click play on the launcher it launches then immediately pops back up with the crash log.

**To Reproduce**

Hit play on twitch
Hit play on Launcher
loads then crashes

**Crash Log**
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option PermSize; support was removed in 8.0
Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Info (please complete the following information):**
 - Modpack Version:  2.77.1
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.`

**Additional context**
I saw a similar crash report on this site before posting this, not sure whether this is a related problem

**Comment by MythicBeast7** [comment]
I've been having the same issue.

**Comment by CalaMariGold** [comment]
Send the full crash log. That doesn't tell us anything
