### ISSUE TITLE
[BUG] Light Bug

### ISSUE THREAD

**Issue by TheDuke92** [CalaMariGold/Rebirth-Of-The-Night#246]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Block emit light without light source

**To Reproduce**
I removed all the torches and light sources from the structure but everything remains illuminated

**Screenshots**
![2020-04-15_03 50 59](https://user-images.githubusercontent.com/63475301/79291025-d67af800-7ecd-11ea-904b-545c0908ec18.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77

**Additional context**
it would seem that the combination of Rustic chandelier + glaretorch and a roof made of slab 
creates lighting problems

**Comment by democat3457** [comment]
Slabs are known to have lighting glitches in vanilla, and I believe the glaretorch light goes through walls (sometimes)
