### ISSUE TITLE
[BUG] Horse jump bar not showing

### ISSUE THREAD

**Issue by Nate-idk** [CalaMariGold/Rebirth-Of-The-Night#248]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
- Visual bug. Horses can still jump, but you can't see the bar that measures the jump, therefore making it difficult to control jump height

**To Reproduce**
- Tame a horse and ride it, then hold space bar

**Expected behavior**
- The bar appearing either above hotbar or bellow exp bar when you mount the horse

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: singleplayer
 - Version the world was created on: 2.77.1

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.
- Because of the HUD being modified, the game doesn't have a place to show the bar. A possible solution is to tweak the HUD and alter the place where it tries to go

**Comment by CalaMariGold** [comment]
Fixed in 2.78
