### ISSUE TITLE
[CRASH] With BetterHUD

### ISSUE THREAD

**Issue by Insane96** [CalaMariGold/Rebirth-Of-The-Night#249]
**Describe the crash**
Sometimes when I look at a specific point (up or down a ladder that goes from surface to bottom of the world) I get this crash

**To Reproduce**
I really don't know, I actually look up or down a ladder I have and the game crashes, but not always

**Crash Log**
https://gist.github.com/Insane96/3a142924a41ed31c6b5d482e3479c160

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77

**Comment by democat3457** [comment]
Is there a sign where you look? It appears that BetterHUD is trying to get a certain raytrace at the location of the sign.

**Comment by Insane96** [comment]
Nope, I was lookin up (and rarely down) a ladder

**Comment by DrunkenUnicyclist** [comment]
I and my clients are having the same issue too. Pretty consistent crash on our main ladder in the beneath. We haven't placed any signs down there yet.

[crash-2020-05-14_23.00.57-client.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4632203/crash-2020-05-14_23.00.57-client.txt)

**Comment by democat3457** [comment]
Hm. Can you open an issue on BetterHUD's GitHub? https://github.com/mccreery/better-hud/issues

**Comment by DrunkenUnicyclist** [comment]
Will do! I just did a little more science, and the crash appears to happen right when I look up beyond the ladder. If I don't look beyond the ladder, all is well.

**Comment by democat3457** [comment]
mccreery/better-hud#90 reference

**Comment by mccreery** [comment]
Quoting myself:
> I haven't been able to reproduce this using Rebirth of the Night, but I'm fairly certain it's fixed by [v1.4.2](https://www.curseforge.com/minecraft/mc-mods/better-hud/files/2963404) that I just released. Please confirm if so.

**Comment by kil0byt3** [comment]
Got it - I'll test today. Thanks for the update, @mccreery <3

**Comment by kil0byt3** [comment]
Looks like we're good. Thanks @mccreery !

@DrunkenUnicyclist - I tested this myself, but I don't have your specific situation, so if you want to test this yourself in your specific setup/on your world that had the issue and let me know if it's fixed, that would be superb. Just need to update the mod manually on server/client. If you can't that's all good!

**Comment by mccreery** [comment]
Glad to do business :) as for your note from 5f2e0ad you will unfortunately have to update again as I found out everyone is having problems with config (mccreery/better-hud#97) - already fixed but please hold out until next update. Thanks!

**Comment by kil0byt3** [comment]
Got it. I was wondering why my config was reset :) Thought it was just my dev enviro acting up. Thanks!

**Comment by mccreery** [comment]
I finally released a version fixing the further config issues in 1.4.2: https://www.curseforge.com/minecraft/mc-mods/better-hud/files/2980723 (might still be processing)

**Comment by kil0byt3** [comment]
Thanks a ton, @mccreery ! 😄
