### ISSUE TITLE
[BUG] harpies and spiders break trapdoors, weirdly

### ISSUE THREAD

**Issue by kil0byt3** [CalaMariGold/Rebirth-Of-The-Night#250]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
but like, just trapdoors, and not other blocks (at least for spiders)

**To Reproduce**
idk, gonna test it

**Expected behavior**
for them not to break trapdoors unless they're meant to

**Screenshots**
i don't have any, i'm making this so I don't forget to fix it

**Additional context**
this is kilo plz don't kill me, this bug report is for my own assistance

**Comment by SandwichHorror** [comment]
Out of spiders, should just be witch spiders as they're the "smartest". They'll also break glass, torches, etc. Intended.
