### ISSUE TITLE
[BUG] Crucible not recycling used tools

### ISSUE THREAD

**Issue by democat3457** [CalaMariGold/Rebirth-Of-The-Night#251]
**Describe the bug**
The crucible is not recycling used tools, even though it is being stoked. 

**To Reproduce**
1. Stoke a fire and put a crucible above it.
2. Put used tools in the crucible.
3. Observe that the tools aren't turning into nuggets.

**Expected behavior**
I expected the tools to get recycled into nuggets.

**Screenshots**
![image](https://user-images.githubusercontent.com/32407067/79406202-096bcd00-7f5c-11ea-854e-9591114b59a4.png)
![image](https://user-images.githubusercontent.com/32407067/79406215-138dcb80-7f5c-11ea-818c-3b27319e7eaf.png)
![image](https://user-images.githubusercontent.com/32407067/79406233-20aaba80-7f5c-11ea-81a0-6f83c287c73c.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77

**Additional context**
I don't know If it matters that the bellows are being powered by a redstone comparator loop (output goes to side)

**Comment by CalaMariGold** [comment]
Fixed in 2.77.1
