### ISSUE TITLE
[BUG] Infinite black basalt blocks

### ISSUE THREAD

**Issue by CrusaderoftheKhan** [CalaMariGold/Rebirth-Of-The-Night#254]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Infinite black basalt blocks. two recipes for the same result. 

**To Reproduce**
Put in a single black basalt brick on 2x2 crafting area (player crafting, not crafting table, but still works there). should see result of 4 smooth black basalt.

**Expected behavior**
No recipe. I expected no recipe for a Single black basalt brick.

**Screenshots**
(images are in discord.)

**Info (please complete the following information):**
 - Modpack Version: 2.7.7.1
 - Server or Singleplayer: SIngleplayer
 - Version the world was created on: 2.7.7.1

**Additional context**
Possible oversight on recipe from mod transfer. possibly not discovered for some time. probably an older issue.

**Comment by kil0byt3** [comment]
got it, thanks

**Comment by cutcat101** [comment]
Fixed in next update
Now each single block conversion between black basalt variants gives you one instead of four
Thanks for the heads up

**Comment by CrusaderoftheKhan** [comment]
Again, No problem. Glad to help.
