### ISSUE TITLE
[BUG] Raw chevron doesnt cook in smoker blocks

### ISSUE THREAD

**Issue by ChewyGogurt** [CalaMariGold/Rebirth-Of-The-Night#257]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
When trying to make raw chevron into cooked chevron inside a smoker it does nothing.

**To Reproduce**
put coal and raw chevron in smoker

**Expected behavior**
nothing will happen

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: singleplayer
 - Version the world was created on: 2.76.1

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by cutcat101** [comment]
Fixed in next update
Thanks for the heads up
