### ISSUE TITLE
[BUG] Rustic Elixir of Regeneration (1:45)/II uncraftable

### ISSUE THREAD

**Issue by gavnook** [CalaMariGold/Rebirth-Of-The-Night#258]
Rustic Elixir of Regeneration (0:45) crafts as expected, but when I add horsetail (or marsh mallow root) in the Advanced Alchemical Condenser, as shown in JEI, the brewing stops. 

To reproduce this, place the ingredients to make this elixir in an Advanced Alchemical Condenser, If the recipe is correct, it will start brewing only when you remove the horsetail. 

I expect that the longer duration version and II version of the elixir to be craftable OR the recipes to be absent from JEI.

- Modpack Version:  2.77.1
 - Server or Singleplayer: Single
 - Version the world was created on: 2.77

**Additional context**
This recipe uses the honeycomb from Harvestcraft. I was unable to brew this elixir at all in 2.76, because they weren't compatible.

**Comment by kil0byt3** [comment]
https://github.com/CalaMariGold/Rebirth-Of-The-Night/pull/265
