### ISSUE TITLE
[BUG] Spawned Above the Nether

### ISSUE THREAD

**Issue by TheNoDieGuy** [CalaMariGold/Rebirth-Of-The-Night#26]
Before the latest update, 2.74, I was trying to get into the nether, but my game crashed whenever I tried. So, I left it for a week (I had other things to do). When I got back, lo and behold I had spawned in the nether! On top of it! With no way down!

On the bright side, mushrooms apparently can grow on bedrock.
![2020-01-17_15 46 52](https://user-images.githubusercontent.com/60017887/72645305-57633b80-3941-11ea-9d17-7eb7ef4576fb.png)

**Comment by TheNoDieGuy** [comment]
Another thing: apparently there's no portal either, so I truly am stuck

**Comment by CalaMariGold** [comment]
This is likely because of the crash you experienced in 2.73. It should not occur in 2.74 worlds.

**Comment by CalaMariGold** [comment]
Can you test this on a new 2.74 world and tell me if you experience the same issue? If not, I'm going to close this

**Comment by TheNoDieGuy** [comment]
That was on a 2.73 world, but the nether hadn’t been generated. I entered into a 2.74 world. In any case, I went into spectator mode and warped into the nether. In any case, the broken portal was solved by turning off shaders.
