### ISSUE TITLE
[BUG] Copper Ingots are not ore-dicted

### ISSUE THREAD

**Issue by Deliphin** [CalaMariGold/Rebirth-Of-The-Night#261]
**Describe the bug**
I've gotten both Simpleores' and Railcraft's copper. They are different, and have different available recipes.

**To Reproduce**
Get both copper ingots, press U (default key for finding uses of block/item) while hovering over it to see the available crafting recipes.

The below are items I've noticed that require `simpleores:copper_ingot` and do not accept `railcraft:ingot:1` (copper ingot).
`quark:pipe`
All of the harvest craft bakeware like potitem, bakewareitem, saucepanitem, etc..
`railcraft:ingot:8` (brass ingot)
`contenttweaker:material_part:4`
`betterwithmods:material:34`
`simpleores:copper_block`
There don't seem to be any items that require `railcraft:ingot:1` and not `simpleores:copper_ingot`.

**Expected behavior**
The copper ingots should have all identical available crafting recipes. They should be treated the same. Even if you don't intend on players being able to get one, you should still be using ore dict entries in recipes so this problem can't come up.

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77.1

**Additional context**
It's a simple fix. You just need to go through the recipes and replace almost every instance of `<simpleores:copper_ingot>` with `<ore:ingotCopper>`, obviously leaving it as-is  on the output of crafting recipes.

**Comment by kil0byt3** [comment]
We don’t have Railcraft in the pack. You added that yourself. Case closed
