### ISSUE TITLE
[BUG] There appears 2 different type of "Coal" in my game as they don't stack.

### ISSUE THREAD

**Issue by Garfink** [CalaMariGold/Rebirth-Of-The-Night#269]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
There appears to be two types of "coal" in my game, I noticed it when some of my coal won't stack in my inventory or in things like a kiln.  They share the same graphics and both function normally in a forge or recipes.  When I hover my mouse over the "coal"s I noticed that one has a "space" in front of the name while the other doesn't have a "space"

**To Reproduce**
Unsure, it just is.  I am not sure where I got the different coal from in-game.  I got around the problem by using up the coal with the lesser amount up, and hopefully it won't crop up again.  But I will keep an eye out for it again in-game if it appears again now that I am concious of it.  

**Expected behavior**
Coal should stack normally.

**Screenshots**
Its not very visual.

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.1

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by democat3457** [comment]
2.77.2?

**Comment by Garfink** [comment]
Oops, I meant 2.77.1

**Comment by BBgunner007** [comment]
There is a similar problem with the sapphire gem.  The usual one that is mined in the overworld is different from the one that spawns in ice dragon loot chests.  They dont stack either but the sapphire from the ice dragon loot chests cant create the armour.

**Comment by democat3457** [comment]
@BBgunner007 what's the id of the sapphire that spawned in the chest? (use /ct hand while holding the gem)

**Comment by democat3457** [comment]
Also, @Garfink if you encounter it again can you give the id of the weird coal? (instructions above)

**Comment by Garfink** [comment]
I will keep an eye out for it.  Now that I am actively modding Minecraft, I know what to look out for.  Thanks.  Hasn't cropped up again so far.

**Comment by BBgunner007** [comment]
I get the following:

Item <iceandfire:sapphire_gem>
OreDict Entries:
-gemSapphire

Item <biomesoplenty:gem:6>
OreDict Entries:
-gemSapphire

@democat3457

**Comment by democat3457** [comment]
Thanks, @BBgunner007 !

**Comment by democat3457** [comment]
Is the ice and fire sapphire used for anything that the biomesoplenty sapphire isn't?

**Comment by kil0byt3** [comment]
They both are oredict, so I doubt it. Not sure why both are showing up

**Comment by democat3457** [comment]
But he also said the armor couldn't be created with the iceandfire sapphire.

**Comment by democat3457** [comment]
Well, unless the duplicate coal pops up again, this issue can be closed. (There's an easy fix anyway :P)
