### ISSUE TITLE
[CRASH] Loading in Shader pack

### ISSUE THREAD

**Issue by Reholas** [CalaMariGold/Rebirth-Of-The-Night#270]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

When loading up the game, Optifine installed, with the recommended shader pack - Sildur's Enhanced Default installed the following crash has occurred. When creating a world with said shader a horrible world visual bug is created. Where the ground and objects are intact but it is as if the physical world is see through/ghostly & separated floating black branches are randomly (or so it appears) are distributed around me. This is a continues problem when loading this shader, I have yet to try the other recommended ones.

**To Reproduce**
Steps to reproduce the behavior: As specified above simply run the downloaded recommended shader - Sildur's Enhanced Default. ++I want to add the resource pack order was also done as asked

**Crash Log**
[crash-2020-04-21_20.31.44-client.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4512288/crash-2020-04-21_20.31.44-client.txt)
 ++Due to the game failing to produce the direct link to the crash report I pasted in the report from the files. Hope this will suffice

**Info (please complete the following information):**
 - Modpack Version: 2.77.1 
              forge-14.23.5.2847
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: Minecraft Version: 1.12.2 (modded) 

**Additional context**
I have no other conclusion other than a possible corrupt mod in the download pack or the shader being so. As you will probably find it could be my own pc's internal relationship to this mod pack and shader. I allocated 7gb of memory to the launch of the mod in the launcher I have 8gb ram total on my pc so this could be another factor for the crash. Hope this was enough information.

**Comment by democat3457** [comment]
You aren't using the latest version of Optifine for 1.12.2, use F5 instead of F4.
