### ISSUE TITLE
[BUG] Easy duping of durable fiber and hemp rope

### ISSUE THREAD

**Issue by Wintryvale** [CalaMariGold/Rebirth-Of-The-Night#277]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
makes infinite durable fibers and hemp rope.

**To Reproduce**
Putting hemp rope into the crafting table produces 6 durable fiber. 6 durable fiber makes 2 hemp rope, making infinite durable fiber.

**Expected behavior**
I was just messing around and found this out. 

**Screenshots**
![image](https://user-images.githubusercontent.com/64224786/80139715-80145600-856c-11ea-8bc4-213da8f86ab0.png)
![image](https://user-images.githubusercontent.com/64224786/80139737-8c98ae80-856c-11ea-9e49-1a9bc23eab1b.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: Server
 - Version the world was created on: 1.77

**Additional context**
Found by accident.

**Comment by kil0byt3** [comment]
This is already fixed in next update - thanks for the report!

**Comment by kil0byt3** [comment]
Fixed by https://github.com/CalaMariGold/Rebirth-Of-The-Night/commit/28b57df0ee49c46d5cd2abde45a5e332471f8402
