### ISSUE TITLE
[BUG] Draconic Sword can't be repaired in the Aetherium Capacitor

### ISSUE THREAD

**Issue by Insane96** [CalaMariGold/Rebirth-Of-The-Night#278]
**Describe the bug**
Draconic Sword can't be repaired in the Aetherium Capacitor

**To Reproduce**
1. Put a Draconic Sword and some Electrum in an Aetherium Capacitor
2. RIP

**Expected behavior**
For the Aetherium Capacitor to repair the Draconic Sword

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77

**Additional context**
I think this happens with the Vampiric Sword too

**Comment by democat3457** [comment]
Well it's not really a bug, the enchanter doesn't show up in the tabs for the item in jei.
