### ISSUE TITLE
Wither Rose not dropping[BUG]

### ISSUE THREAD

**Issue by BBgunner007** [CalaMariGold/Rebirth-Of-The-Night#279]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
When the wither kills mobs, a wither rose should drop.  Since all the passive mobs are not vanilla (I think they are from the animania mod), the drops do not seem to be happening.

**To Reproduce**
Spawn a wither and allow it to kill different types of mobs.

**Expected behavior**
The wither should kill a mob and a wither rose will drop. This is important for the sword True Darks Edge as it is in the recipe for the Heart Of The Fallen.

**Screenshots**
Not needed

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.1

**Additional context**
My guess is that the drop only occurs with vanilla mobs. One mob I haven't tested it on yet is dogs/wolfs which might still drop them.

**Comment by democat3457** [comment]
Will be craftable next version, 952a96c1ddfc1a9729b8fe1913ff33ded4e0f56c

**Comment by democat3457** [comment]
Still a bug, but a workaround is in place. Should it be closed?
