### ISSUE TITLE
[CRASH] lighting a fire near ebony wood siding causes a game crash

### ISSUE THREAD

**Issue by Calvin304** [CalaMariGold/Rebirth-Of-The-Night#28]
see title
https://paste.dimdev.org/livuqudifi.mccrash

**Comment by HeyItsKairu** [comment]
Hello, could you please provide a crash log and perhaps a screenshot or two as well? It would help me a lot with identifying how to reproduce and fix this crash.

Thanks in advance!

**Comment by HeyItsKairu** [comment]
Tested and recreated. I have submitted an [issue](https://gitlab.com/BetterWithMods/1.12/BetterWithMods/issues/1347) to the BWM page.

**Comment by CalaMariGold** [comment]
Duplicate of #69
