### ISSUE TITLE
[BUG]Shift click crafting with stacked runes dupes the runes

### ISSUE THREAD

**Issue by elephantae** [CalaMariGold/Rebirth-Of-The-Night#280]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
When the player uses stacked runes to craft with shift click, a copy of the stack goes into the player's inventory for every iteration of the craft. For example if the player has 3 stacked disintegration runes and 3 wormhole potions and shift clicks the output, they would get 1 stack of 3 runes, 1 stack of 2 runes and 1 stack of 1 rune in their inventory.

**To Reproduce**
Steps to reproduce the behavior:grab a stack of disintegration runes(easiest to demonstrate) and a stack of item to be disintegrated, put them in the crafting grid and shift click the output.

**Expected behavior**
The runes are expected to either be used 1 durability from each or sequentially, and not be duplicated.

**Screenshots**
It's not too visual.

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer:Server
 - Version the world was created on:2.77.1

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by SandwichHorror** [comment]
known bug, will be fixed in 2.78

**Comment by Kompreya** [comment]
Fixed in next release. Runes are no longer stackable.
