### ISSUE TITLE
[BUG] Red Granite Iron Ore looks just like Red Granite Blocks

### ISSUE THREAD

**Issue by JustinLTu** [CalaMariGold/Rebirth-Of-The-Night#285]
**Describe the bug**
Red Granite Iron Ore looks like exactly like regular Red Granite blocks. See screenshot for example.

**To Reproduce**
Unsure. Might be all Red Granite Ore, or just the specific vein in screenshot.

**Expected behavior**
I expected Red Granite Iron Ore to look more distinct from regular Red Granite blocks

**Screenshots**
![Camoflauged Red Granite Iron Ore](https://user-images.githubusercontent.com/13356915/80293531-053a6f00-8715-11ea-850d-cbfc5a74484f.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.1

**Additional context**

**Comment by SandwichHorror** [comment]
it's a "feature", bug Mari about it :man_shrugging:
