### ISSUE TITLE
[CRASH] Random Crashes During Any Time

### ISSUE THREAD

**Issue by FanMaNSTan** [CalaMariGold/Rebirth-Of-The-Night#287]
Describe the crash
I randomly crash when walking around. I am normally stuck for like a minute until I have the ability to close the game but other times my fps drastically drops and I can't even close the game or get back to my desktop so I have to hard restart my laptop. I have 6 GB of ram allocated

To Reproduce
I don't know if the behavior can be reproduced, I am just walking around when it happens

Crash Log
https://pastebin.com/FrMqCqG8

Info (please complete the following information):
 - Modpack Version: 2.77.1
 - Server or Singleplayer: Both
 - Version the world was created on: expansive (world wipes every version)

Additional context
I do believe that multimc was a reason to why it crashed as frequently as it did but now its not as bad but it still happens.

**Comment by democat3457** [comment]
The log mentions null chunk loading, does it happen on a new world?

**Comment by FanMaNSTan** [comment]
Sorry for not responding until now, it happened on any world I played on,
no matter if it was new or already played on by previous players.

**Comment by democat3457** [comment]
Thanks for the reply, have you tried a fresh install?

**Comment by FanMaNSTan** [comment]
Not exactly, I have dropped ROTN for right now though.

**Comment by democat3457** [comment]
Aight. Let us know when you return :D
