### ISSUE TITLE
[BUG] Curse of binding armor removable in advanced enchantment table

### ISSUE THREAD

**Issue by DovydasAL** [CalaMariGold/Rebirth-Of-The-Night#297]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
If a piece of armor has curse of binding, in can be removed in the GUI for the advanced enchantment Table

**To Reproduce**
1. Have armor with curse of binding
2. Remove it in advanced enchantment table

**Expected behavior**
Armor should not be removable 

**Info (please complete the following information):**
 - Modpack Version: 2.771
 - Server or Singleplayer: Server
 - Version the world was created on: 2.771

**Comment by SandwichHorror** [comment]
intended
