### ISSUE TITLE
Xray Pick

### ISSUE THREAD

**Issue by lizelive** [CalaMariGold/Rebirth-Of-The-Night#3]
![image](https://user-images.githubusercontent.com/40217331/71630990-03bfc680-2bbb-11ea-833b-442fc314dfea.png)
Allows you to see underground with some ores when using a pickaxe as of bc79d8deb864ef857dfa94bccf5efc0025d50857

**Comment by CalaMariGold** [comment]
Fixed in 2.71.  Mythril and Viridium still have this issue and it is being worked on.
