### ISSUE TITLE
[CRASH] BWM fogColor crash

### ISSUE THREAD

**Issue by Umber0010** [CalaMariGold/Rebirth-Of-The-Night#30]
all in the title really, I was lagging a good bit in the nether, tried to turn my render distance down from 12 to 11, and the game booted me from the world. The game was able to remain open though

Go to nether, lower render distance

The world should Crash, say that Better with mods caused an issue, and then you should have the option to either get the crash log or go to the title screen

uhhh, I got the crash log, does that help? https://paste.dimdev.org/ewuxemapik.mccrash

 - Modpack Version: 2.74
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: No idea. sorry. The nether wasn't generated until 2.74 though

**Comment by Umber0010** [comment]
Update: It seems that it's not the nether that causes the crash, but rather adjusting the render distance while heavy lag in general that causes the issue

New Steps to relicate: Get into any situation that causes significant lagg (Fighting an excessive ammount of Strays will do), Adjust render distance

**Comment by CalaMariGold** [comment]
@HeyItsKairu Didn't we fix this by disabling fog in the Nether? Maybe its a bwm issue?

  `  at betterwithmods.module.tweaks.VisibleStorms.fogColor(VisibleStorms.java:154)`

**Comment by HeyItsKairu** [comment]
I believe we did, it is certainly a better with mods issue. I believe it has been reported and labeled to fix.

**Comment by CalaMariGold** [comment]
Wait, @HeyItsKairu reported where? BWM is no longer being updated.

**Comment by CalaMariGold** [comment]
Fixed in 2.75.2 by disabling VisualStorms. Because of this, you won't know when it is storming in desert biomes, but windmills will still break during them. Also, no more Nether storms.
