### ISSUE TITLE
[BUG] Saw mill gives oak bark for Spruce wood

### ISSUE THREAD

**Issue by JustinLTu** [CalaMariGold/Rebirth-Of-The-Night#301]
**Describe the bug**
Whenever you use the mechanical saw mill from Better with Mods to cut Spruce logs, you're given Oak Bark

**To Reproduce**
Place an Spruce log onto an active sawmill. When the log is cut, you're given oak bark.

**Expected behavior**
I expected spruce bark to come from sawing Spruce logs.

**Screenshots**
![image](https://user-images.githubusercontent.com/13356915/80872636-ffd6aa80-8c67-11ea-92a2-ea85cf3b4be4.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.1

**Additional context**
None

**Comment by Foreck1** [comment]
Thanks for the report, as of the 2.77.1 update though, the bark item has been made generic for all woodtypes. Now it's just "wood bark", therefore this is working as intended.
