### ISSUE TITLE
[BUG] Strange happenings in multiplayer

### ISSUE THREAD

**Issue by Cootaloo** [CalaMariGold/Rebirth-Of-The-Night#303]
**Describe the bug**
When playing with friend through LAN, a couple things seem off. Mainly when I pick up items I don't see the notification in the bottom right. Instead my friend does, along with his own. Which is odd. I also don't see the test above the hotbar that shows where you are. Like "The Wilds" or whatever. I have suspicious that we have a few textures different too, but I'm not 100% sure.

**To Reproduce**
Play through LAN I suppose. We use hamachi but I don't think that should make a difference.

**Expected behavior**
Being able to see my pickups and everything normally.

**Screenshots**
[None]
**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: LAN
 - Version the world was created on: 2.77.1

**Additional context**
[None]

**Comment by kil0byt3** [comment]
Unfortunately playing through LAN isn’t supported and I believe that’s on the Curseforge page - if not, I’ll add it. There’s a few bugs like this with many mods when playing via LAN. You’ll have to set up a server - sorry for the inconvenience.
