### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Relyt026** [CalaMariGold/Rebirth-Of-The-Night#304]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Blocks not dropping after a Davinci's Vessels bug.

**To Reproduce**
Sometimes if you assemble a big airship using the Davinci's Vessels mod it happens that about 80% of it get deleted. Then any blocks that you mine wont drop

**Expected behavior**
Normally after assembling an airship you should be able to fly it.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: Server 
 - Version the world was created on: 2.77.1

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by kil0byt3** [comment]
Davinci's will be replaced soon - there are a LOT of bugs. We'll have an alternative mod
