### ISSUE TITLE
[BUG] Strawberry Slimes Spawning Before Going Into Nether

### ISSUE THREAD

**Issue by CraftingMantis** [CalaMariGold/Rebirth-Of-The-Night#31]
The version I am currently using is a single player world on 2.74, which was originally created in version 2.7. I noticed that strawberry slimes were spawning in my caves even though I had not entered the nether. I checked out incontrol spawn json and found the below. I believe it is supposed to say strawberry slime instead of blueberry slime in the bottom section.

  {
    "dimension": 0,
    "mob": "specialmobs:strawberryslime",
    "random": 0.01,
    "maxlight": 15,
    "minlight": 14,
    "seesky": true,
    "gamestage": "enteredNether",
    "maxcount": {
        "amount": 2,
        "perplayer": true
    },
    "result": "allow"
 },
 {
    "dimension": 0,
    "mob": "specialmobs:blueberryslime",
    "result": "deny"
 },

**Comment by CalaMariGold** [comment]
Good catch! Thank you! Fixed in 2.75.

**Comment by CraftingMantis** [comment]
Awesome! Glad I could help!
