### ISSUE TITLE
[BUG]Both variants of aperture and dragonforge brick create buggy blocks when pushed or pulled with pistons

### ISSUE THREAD

**Issue by elephantae** [CalaMariGold/Rebirth-Of-The-Night#310]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
oh boy, this one's a weird one. When pushed or pulled with pistons or sticky pistons, fire dragonforge bricks, ice dragonforge bricks, fire dragonforge inputs and ice dragonforge inputs, in addition to being pushed or pulled into their new location, turn into invisible, impossible to interact with blocks and is not fixed upon relogging or restarting. In addition, despite being movable by piston blocks, these blocks are immovable by the dungeontactics portable piston devices. The invisible blocks are not selectable and cannot have blocks placed off of them or inside their position. Mobs try to pathfind as if they were blocks, but fall through them. Water and lava do not flow through them.

**To Reproduce**
Push or pull one of the aforementioned blocks. Also try using a dungeontactics portable piston device on one.

**Expected behavior**
I expect the block to be moved and not become a glitched state, also I expect all piston-movable blocks to be movable by the portable piston device.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer:both
 - Version the world was created on:2.77.1

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by kil0byt3** [comment]
probably an I&F issue? opened an issue, waiting

**Comment by kil0byt3** [comment]
Looks like this was fixed with https://github.com/Alex-the-666/Ice_and_Fire/commit/04c2bf7bad8f0b1cfb9b47a51cc3ac166a54feae
