### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by yareyaredazeu** [CalaMariGold/Rebirth-Of-The-Night#313]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
A clear and concise description of what happened when you crash. Also, tell us if it continues to crash on world join or if it was a one time thing.

Since you can't enchant a light's edge, putting it into the True Enchant Table crashes the game. Crashes once and then is fine until you do it again.

**To Reproduce**

Drop a light's edge into a true enchantment table

**Crash Log**
Click "Get Link" from the crash and paste it here. Or post the log if it's a server.
[crash-2020-05-06_14.40.47-client
[crash-2020-05-06_14.40.47-client.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4589607/crash-2020-05-06_14.40.47-client.txt)
.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4589604/crash-2020-05-06_14.40.47-client.txt)

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: server
 - Version the world was created on: no idea

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.
probably because lights edge isnt meant to be enchanted

**Comment by democat3457** [comment]
does dark's edge also do this?

**Comment by kil0byt3** [comment]
Mari will fix - it's on our tracked issues. Waiting for a mod update that fixes this https://github.com/CalaMariGold/Rebirth-Of-The-Night/pull/315#issuecomment-626416537

**Comment by kil0byt3** [comment]
And mod issue with PR, for reference: https://github.com/Epoxide-Software/Enchanting-Plus/pull/165
