### ISSUE TITLE
[CRASH] ActualMusic : Main Thread

### ISSUE THREAD

**Issue by Raykemono** [CalaMariGold/Rebirth-Of-The-Night#319]
[CRASH] ActualMusic : Main Thread

i can't enter the aether crash every time when i'm in aether. i try to remove Embassy and ActualMusic is work i can get in aether.

 - Modpack Version : 2.77.1
 - Server or Singleplayer : Server with friend
 - Version the world was created on : 2.77.1

[hs_err_pid15184.log](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4603384/hs_err_pid15184.log)

**Comment by Eksekk** [comment]
Already known (#160), unfortunately no fix yet.

**Comment by democat3457** [comment]
@Raykemono uninstall any newer java versions, it appears that actualmusic is running on those instead of java 8.

**Comment by Raykemono** [comment]
oh.... okay
