### ISSUE TITLE
[BUG] Can't shift-right click new chests to move them.

### ISSUE THREAD

**Issue by Cryloc** [CalaMariGold/Rebirth-Of-The-Night#327]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
With "Wood" chests you cannot move them as a whole (like you can with regular wooden chests.)

**To Reproduce**
Add older non-"wood" chest such as Wooden chest, next to a new chest Oak wood chest.

**Expected behavior**
With an empty hand, one should be able to shift-right click and move the entire chest. However with the new wooden chests, it doesn't.

**Screenshots**
Not needed.

**Info (please complete the following information):**
 - Modpack Version: v2.77.2
 - Server or Singleplayer: server
 - Version the world was created on: v2.77.1

**Additional context**
The new chests don't have the same functionality with whatever mod allows you to move chests. Perhaps added them to that mod's allowed chest-moving.

**Comment by CalaMariGold** [comment]
Will fix in 2.7.8

**Comment by kil0byt3** [comment]
fixed in https://github.com/CalaMariGold/Rebirth-Of-The-Night/commit/2b12f6ac850683cb397289751891d1f0fd380fc4 for incoming hotfix

**Comment by kil0byt3** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[DONE] carryon for new chests](https://trello.com/c/pEYHY8Gv/1118-done-carryon-for-new-chests)
