### ISSUE TITLE
[BUG] automatically dismounting Davinci's Airship

### ISSUE THREAD

**Issue by totalDesolation** [CalaMariGold/Rebirth-Of-The-Night#329]
Description: Attemptin to climb into an assembled and functioning Davinci's Airship, fall out of it after driving for short duration. 

How to replicate: Assemble and embark a Davinci's Airship and attempt to drive it for a short time

What should happen: The airship should be capable of being driven however far as necessary with full fuel and proper assembly

Info
 - Version played on: 2.77.2.1
 - Singleplayer or server: Singleplayer
 - Version world was made on: 2.76

**Comment by CalaMariGold** [comment]
We're removing this mod soon.
