### ISSUE TITLE
[BUG] music overlapping in aether

### ISSUE THREAD

**Issue by manlyastronaut** [CalaMariGold/Rebirth-Of-The-Night#33]
Aether music and custom music are overlapping

Go in the Aether with custom music on

The two music will play on top of each other

 - Modpack Version: 2.74
 - Server or Singleplayer: server
 - Version the world was created on: 2.72

**Comment by CalaMariGold** [comment]
Weird, are you sure? I'm almost positive I fixed this awhile ago. Can anyone else confirm this? Any other details you can give about what you were doing in the Aether?

**Comment by CalaMariGold** [comment]
Fixed in 2.75.
