### ISSUE TITLE
[BUG] Invasion occuring immediately upon updating

### ISSUE THREAD

**Issue by totalDesolation** [CalaMariGold/Rebirth-Of-The-Night#330]
**Describe the bug**
upon joining a world from 1.77.2.1, an invasion started in the third quarter of the night which it had been left off at before closing the world after 1.77.2

**To Reproduce**
open a world from 1.77.2 during the night directly after updating to 1.77.2.1

**Expected behavior**
the invasion status and schedule should follow from the previous session, in the previous version.

**Info (please complete the following information):**
 - Modpack Version: 1.77.2.1
 - Server or Singleplayer: Singleplayer 
 - Version the world was created on: 1.76

**Comment by democat3457** [comment]
Likely a bug with resetting because the invasion time was changed to 9 days instead of 7.
