### ISSUE TITLE
[BUG] Ironberries insane jumps

### ISSUE THREAD

**Issue by TBiscuit1** [CalaMariGold/Rebirth-Of-The-Night#331]
**Describe the bug**
After eating ironberries, you can jump insanely high

**To Reproduce**
Eat a Ironberry
Jump (Hold the space bar to jump higher)

**Expected behavior**
You normally can't jump after eating ironberries

**Screenshots**
https://youtu.be/zITTgIRVzc0 <-----

**Info (please complete the following information):**
 - Modpack Version: 2.77.2.1
 - Server or Singleplayer: Singleplayer, but Multiplayer should do the same bug
 - Version the world was created on: 2.77.2.1

**Additional context**
It's probably because ironberries give a very high jumpboost that make you normally unable to jump, but a mod (I sadly don't know which one) is causing this, I will try to find the mod, I know that the mod walljump can cause this but it's not in the pack, so it can't be that mod

**Comment by democat3457** [comment]
Can confirm. Also you don't take fall damage since you get resistance form eating ironberries.

**Comment by CalaMariGold** [comment]
https://github.com/CalaMariGold/Rebirth-Of-The-Night/issues/66
