### ISSUE TITLE
[BUG] Bronze weapons have weak durability

### ISSUE THREAD

**Issue by Eksekk** [CalaMariGold/Rebirth-Of-The-Night#332]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
In title.

**To Reproduce**
N/A

**Expected behavior**
Better durability.

**Screenshots**
N/A

**Info (please complete the following information):**
 - Modpack Version: 2.77.2
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.1

**Additional context**
N/A

**Comment by CalaMariGold** [comment]
Can you be a bit more specific so we don't have to spend 15 minutes opening up the game and looking at durability?

**Comment by democat3457** [comment]
<img width="475" alt="Screen Shot 2020-05-13 at 3 56 45 PM" src="https://user-images.githubusercontent.com/32407067/81864509-5bd7e380-9532-11ea-8c95-1e7204ea521b.png">

**Comment by CalaMariGold** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [fix bronze durability](https://trello.com/c/uebdHNqq/1117-fix-bronze-durability)

**Comment by Eksekk** [comment]
Also saber. Will open the game in a minute and write all weak durabilities.

**Comment by Eksekk** [comment]
Okay, so basically ALL bronze weapons except gladius got wrong durability.

**Comment by kil0byt3** [comment]
got it, i'll have it in the 2.77.3 hotfix
