### ISSUE TITLE
[BUG] Obsidian level hardness for UB stone bricks and indestructible stone brick walls

### ISSUE THREAD

**Issue by Topkekm9** [CalaMariGold/Rebirth-Of-The-Night#338]
**Describe the bug**
All stone brick blocks and slabs from Underground Biomes have absurd level of hardness comparable to obsidian.
What is worse, most UB stone brick walls (Red Granite, Black Granite, Rhyolite, Andesite, Gabbro, Basalt, Koamtiite, Dacite, Gneiss) have mining level of **20**, rendering them indestructible.

**To Reproduce**
Simply place said blocks in either creative or survival and attempt to mine

**Expected behavior**
Brick blocks and slabs having their hardness level same as their respective cobblestones and brick walls having mining level "Stone" just like the rest of the walls

**Screenshots**
![image](https://user-images.githubusercontent.com/65262352/81820107-79a44900-9530-11ea-88a2-d58af148272c.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77.2.1
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.2.1

**Additional context**

**Comment by kil0byt3** [comment]
stone bricks and slabs will be fixed too for hotfix, fyi

**Comment by kil0byt3** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix brick hardness](https://trello.com/c/VBqyndmO/1109-fix-brick-hardness)
