### ISSUE TITLE
[BUG] sprelunking totem in Aether

### ISSUE THREAD

**Issue by manlyastronaut** [CalaMariGold/Rebirth-Of-The-Night#34]
The sprelunking totem doesn't work with aether ores (may be a feature)

Activate a sprelunking totem near ores in the Aether

The small totem heads won't appear.

 - Modpack Version: 2.74
 - Server or Singleplayer: server
 - Version the world was created on: 2.72

If I place overworld ores it works just fine on them.

**Comment by CalaMariGold** [comment]
Thanks, we can adjust the config to allow for Aether ores as long as they have an ore dictionary. We'll look into this.

**Comment by HeyItsKairu** [comment]
Fixed in version 2.75.
