### ISSUE TITLE
[BUG] Unable to craft Skyroot Sticks

### ISSUE THREAD

**Issue by democat3457** [CalaMariGold/Rebirth-Of-The-Night#341]
**Describe the bug**
One is unable to craft skyroot sticks for many things, including ambrosium torches and skyroot tools.

**To Reproduce**
1. Attempt to craft skyroot sticks.
2. Observe that the output is regular sticks.

**Expected behavior**
For skyroot planks to turn into skyroot sticks.

**Screenshots**
N/A

**Info (please complete the following information):**
 - Modpack Version: 2.77.2.1
 - Server or Singleplayer: SP
 - Version the world was created on: 2.77.2.1

**Additional context**
Likely caused by the stick recipe taking priority over the skyroot stick recipe. (However, you can't change the priority of a recipe through CT)

**Comment by CalaMariGold** [comment]
I thought @cutcat101 fixed it so that skyroot tools take normal sticks

**Comment by democat3457** [comment]
![image](https://user-images.githubusercontent.com/32407067/81856213-1c0aff00-9526-11ea-8f85-76063610b469.png)
nope.

**Comment by democat3457** [comment]
![image](https://user-images.githubusercontent.com/32407067/81856275-304efc00-9526-11ea-935c-dd0dfbda1099.png)

**Comment by democat3457** [comment]
Fixed by c724977dee008c4d7d787be31e3e10752ce41c52
