### ISSUE TITLE
Lots of Whales in Twilight lake in the TF

### ISSUE THREAD

**Issue by Spoofygamer** [CalaMariGold/Rebirth-Of-The-Night#350]
Lots of whales are spawning in mass groupings and constantly spawning in the TF lakes.
![2020-05-18_12 12 53](https://user-images.githubusercontent.com/38812100/82236005-78449900-9901-11ea-9264-817f5c6ebe79.png)

**Comment by democat3457** [comment]
Version?

**Comment by democat3457** [comment]
I believe I may know why - no other animal is set to spawn in the twilight_lake biome, so there are massive amounts of whales spawning.

**Comment by democat3457** [comment]
However, the Twilight Forest isn't going to be changed anytime soon, so we will keep this issue on the back burner. Thanks for reporting anyway!

**Comment by democat3457** [comment]
Fixed by c1f0209de109f7fc4dee7e4908cb4aca4e0c4ad0
