### ISSUE TITLE
Empty Parameters Detected while loading world

### ISSUE THREAD

**Issue by AdityaKumar5155** [CalaMariGold/Rebirth-Of-The-Night#354]
After updating my instance from 1.77.1 to 1.77.4. When i load my world it says "3 Empty Parameters found, if you'll proceed then these parameters will removed. " So, should i proceed to load world or not?

**Comment by democat3457** [comment]
can you send a screenshot of the warning?

**Comment by democat3457** [comment]
@AdityaKumar5155 ^

**Comment by democat3457** [comment]
This is likely an outdated question now so I'll close it, but you should most likely be fine loading your world. Always make backups before loading new worlds so you don't lose your data!
