### ISSUE TITLE
Aether sun spirit chest bug

### ISSUE THREAD

**Issue by MrSam79** [CalaMariGold/Rebirth-Of-The-Night#357]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Every time I've killed a sun fire god in aether and opened the chest it only had multiple vampire swords and nothing else. The boss is very annoying to kill and the rewards are good, but only getting the same reward every time isn't so rewarding anymore. 

**To Reproduce**
Just kill the boss, open the chest and you find vampire swords only.

**Expected behavior**
I've tested it a few times because the boss is very annoying to kill but the results were still the same, there were only vampire swords in the chest after killing the boss.

**Screenshots**
![image](https://user-images.githubusercontent.com/65853421/82753257-f9ea6a00-9dcc-11ea-961b-53df2e6bdd50.png)
![image](https://user-images.githubusercontent.com/65853421/82753270-171f3880-9dcd-11ea-80db-da73390aee07.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77.4
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.4

**Additional context**
Nothing to add here. I don't know why it only had vampire swords in a chest instead of its many other rewards.

**Comment by kil0byt3** [comment]
Thanks for your report! I do believe this is fixed in the AEble and/or Aether updates already, and will be fixed in next version of RotN. (either way the update for Aether made those dungeon loot chests work off of loot tables, so we can adjust the dungeon loot ourselves, which is great!)
