### ISSUE TITLE
[BUG] Ships Helm/Steam-Engine [USING SHIPS] 

### ISSUE THREAD

**Issue by CristoZDG** [CalaMariGold/Rebirth-Of-The-Night#363]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
When using a Ships Helm and Steam-Engine, caused several glitches. When aligning, and dis-assembling our ship we encountered our first dupe with certain placed items on the ship duping into our inventories (Kilns). The second bug when re-aligning after moving the ship resulted in half the ship to dupe by clicking dis-assemble. 
The last bug which was the most unfortunate, once we were done moving the ship, any block we broke in the overworld on the server would not drop. ex: breaks grass block, nothing drops.
Even after server restarts the entire world was bugged and unplayable [We have backups but will see a rollback :( ]
**To Reproduce**
Using DaVinci's ships, aligning re-aligning etc. [normal ship not air ship]
**Expected behavior**
We expected to be able to move the ship location and continue playing from the pirate ship. Move and park in new location.
**Screenshots**
![2020-05-29_14 55 56](https://user-images.githubusercontent.com/55932210/83295380-da808200-a1bc-11ea-8e79-3ca606f30c0d.png)
![2020-05-29_14 59 10](https://user-images.githubusercontent.com/55932210/83295453-fbe16e00-a1bc-11ea-94f2-d48d6aa217cf.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77.4
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77.4
**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.
Clicking Disassemble seems to cause the issue.

**Comment by democat3457** [comment]
Well. 'Tis an unfortunate problem since DaVinci's is known to be extremely buggy. In fact, DaVinci's Vessels is removed in 2.78 with no alternatives yet due to this bugginess. Additionally, the mod's development is very inactive as the last commit for 1.12 was in 2019, so sadly this is a bug that cannot be fixed :frowning:
