### ISSUE TITLE
[BUG]Regular redstone repeater recipe doesn't work even though new recipe uses exact same amount of resources

### ISSUE THREAD

**Issue by kil0byt3** [CalaMariGold/Rebirth-Of-The-Night#365]
Cannot verify this right now because I have no game instance in front of me, but if someone could follow up that would be legendary

**Describe the bug**
Regular redstone repeater recipe doesn't work even though new recipe uses exact same amount of resources, enable old recipe too please.

**Comment by JartanFTW** [comment]
Can confirm, only redstone repeater recipe requires the items (and their alternatives) in the following image.
https://imgur.com/a/LosENOi

When trying to use regular recipe it doesn't let you:
https://imgur.com/a/zOHaQgw
