### ISSUE TITLE
[CRASH] server crashing on startup

### ISSUE THREAD

**Issue by xXParryXx** [CalaMariGold/Rebirth-Of-The-Night#377]
**Describe the crash**
Sadly don't really know how to describe it except that it is withing 5 seconds of starting the server

**To Reproduce**
Don't know how sadly

**Crash Log**
[latest.log](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4753184/latest.log)

**Info (please complete the following information):**
1.77.5
 server side
 world created on 1.77.3
tested also with a brand new world but the server doesn't even get that far

**Additional context**
It might be because of the server hosting service that my group is using that is ggserver.com but the previous versions had no issue at all and used them for a long time(with other mod-packs)

**Comment by democat3457** [comment]
Are you using the server pack and not the client pack?

**Comment by xXParryXx** [comment]
yeah its using the server version of the pack

**Comment by democat3457** [comment]
It appears that when updating, the old mods remained in the mods folder, resulting in duplicate mods with different versions being loaded. This probably caused the problem.

**Comment by xXParryXx** [comment]
well i managed to fix it as i did a complete wipe of the server files(saved the world in a safe place) and reinstalling it.
