### ISSUE TITLE
[BUG]? Issue with textures/lightning of beneath ores (Viridium, Mythril)

### ISSUE THREAD

**Issue by notbanndusername** [CalaMariGold/Rebirth-Of-The-Night#378]
**Describe the bug**
It happens every time I enter the beneath, It makes so easy to find the ores, idk if other ppl is having the same issue

**To Reproduce**
Just went to the beneath lmao

**Screenshots**
https://imgur.com/a/6zPlNSr

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.4

**Additional context**
Using Sildurs Shaders Medium.
It only works on generated blocks. Placed blocks doesnt have that issue

**Comment by democat3457** [comment]
Sildur's Enhanced Default is the only Sildur's shader that is supported. Bugs will be found on other Sildur's shaders, such as yours.
