### ISSUE TITLE
[BUG] Finally found what cause ironberries flight!

### ISSUE THREAD

**Issue by TBiscuit1** [CalaMariGold/Rebirth-Of-The-Night#379]
I did made a issue about ironberries but I found what cause this and how to correct it

**Describe the bug**
There is a "bug" that cause ironberry to give an insane jump boost

**To Reproduce**
The ironberry flight is simple, eat one and hold space bar

**Expected behavior**
Normally, ironberries make you unable to jump by giving you a very high jump boost

**Screenshots**
Nope

**Info (please complete the following information):**
Not necessary to give these info, it's just to show how to correct this

**Additional context**
1. Which mod cause this "bug"?
Potion Core
2. How this happen?
Ironberries give you a very high jump boost, normally it makes the player unable to jump, but, potion core allow the player to control how high there jump are, since it's a very high jump boost (over lvl 127!) you can almost fly.
3. How to correct it?
In the Potion Core config, you can turn on and off controllable jump boost, sadly, turning it off also make normal jump boost unable to control, but seriously, with enought ironberries you can literraly say "Nope I'm not fighting this thing!" and fly up so high that the mob can't see you anymore. You could even skip a whole invasion with enought ironberries! (need a lot of them since the jump boost thing last around 10s and night are really long, but a full inv of ironberries could do the work)

**Comment by TBiscuit1** [comment]
Well... yes, but you can use water

**Comment by TBiscuit1** [comment]
Just fall into a river each time you fall and you can easly skip a whole invasion/night

**Comment by yeelp** [comment]
>    In the Potion Core config, you can turn on and off controllable jump boost

This actually isn't necessary. PotionCore adds a Weight potion effect which you can just give the player when they eat an Ironberry using CraftTweaker. At a strength of 30 (and maybe even lower), a player essentially can't jump at all, no matter what strength Jump Boost they have.

Subscribing (or whatever you call it for CraftTweaker events) to [LivingEntityUseItem.Finish](https://docs.blamejared.com/1.12/en/Vanilla/Events/Events/LivingEntityUseItem) ought to be the way to do it.

**Comment by TBiscuit1** [comment]
yeah I didn't thinked about the weight potion effect, really good idea, I think even the creator of the mod should add this if potion core is there

**Comment by TBiscuit1** [comment]
Ok, so I tried to avoid a whole invasion with nothing except 64 ironberries and I easly managed to do it, it's really op but also really fun to do, I would be sad if this is patched. I seriously would like to see someone do it in the SMP server X)

**Comment by democat3457** [comment]
Wow, CT has event support?! That's awesome!

**Comment by democat3457** [comment]
Fixed in this commit: https://github.com/CalaMariGold/Rebirth-Of-The-Night/commit/a81c057d5e5c7d43876e814291c1ec414e8fdedb

**Comment by yeelp** [comment]
Perhaps a mid to late game custom brewable potion (most likely added by CraftTweaker) that replicates the pre-patch Ironberries (with a slightly extended duration for the base potion, maybe 30 seconds) could be a nice homage? Not sure about exact details for the recipe itself, but it'd be a cool throwback I guess.
