### ISSUE TITLE
(BUG) Duplication Glitch/Bug

### ISSUE THREAD

**Issue by MaybeNotACow** [CalaMariGold/Rebirth-Of-The-Night#38]
Description: The Unique Weapon 'Draconic Sword', enchanted with the following enchantments (Keen Edge I, Sharpness III, Scorn, Salvage, Unbreaking III) and at minimal durability, when placed into an item frame mounted vertically upon a wall, will slot the sword into the frame, while making an 'item pop' sound and dropped a duplicate of that sword on the ground. Both weapons shared durability and enchantments, can be replicated.

Proof: See images and attached video.

![Desktop Screenshot 2020 01 25 - 11 02 47 36](https://user-images.githubusercontent.com/60295319/73123960-8f7f0580-3f63-11ea-9796-cc9d22debf57.png)

---

https://drive.google.com/open?id=1CWF-9ftN9d2XJLCzUiSNFLEJpmen8HFG

Thank you,

Grandpa Cow

**Comment by SandwichHorror** [comment]
Unfortunately the Salvage enchantment had to be disabled due to this bug. It'll be fixed in 2.75. Thanks for the report. It's a known issue for Charm dev since late August - we can just hope it gets fixed sometime in the future so we can enjoy this enchantment.
