### ISSUE TITLE
[BUG] Eclogite brick slab turns to Black granite brick slab when picked

### ISSUE THREAD

**Issue by DapsterDan** [CalaMariGold/Rebirth-Of-The-Night#385]
**Describe the bug**
When picked an Eclogite Brick Slab becomes a Black Granite Brick Slab.

**To Reproduce**
Place an Eclogite Brick Slab and pick it.

**Expected behavior**
Should get an Eclogite Brick Slab back.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77.4

**Additional context**

**Comment by SandwichHorror** [comment]
duplicate of #362
