### ISSUE TITLE
[BUG] Haunted Tool Drops Uncraftable Tools

### ISSUE THREAD

**Issue by Areorah** [CalaMariGold/Rebirth-Of-The-Night#386]
**Describe the bug**
I was able to retrieve a tin axe from killing a haunted tool that was a tin axe. I haven't seen any other 

**To Reproduce**
Kill a haunted tool that has an uncraftable tool, like a tin axe.

**Expected behavior**
Shouldn't uncraftable tools not be obtained from haunted tools like a tin axe? I am not entirely sure if this is intentional or not.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.5

**Additional context**

**Comment by SandwichHorror** [comment]
Congratulations, you have found my rare but silly reference to the Tin Man from the Wizard of Oz
