### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SwordMaster3341** [CalaMariGold/Rebirth-Of-The-Night#393]
**Describe the bug**

**To Reproduce**
1. Get the air balloon set up
2. Click assemble ship
3.Watch as when you leave you are put randomly in the sky and cannot move
**Expected behavior**

What is supposed to happen is the airship is supposed to fly

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.5

**Additional context**
 Make sure to leave the ship. I also think that when building the balloons in a square with that installed could have glitched it out

**Comment by democat3457** [comment]
Unfortunately, we won't be fixing this because DaVinci's is known to be buggy and is getting removed next version because it can potentially crash and corrupt worlds. We appreciate your bug report, though!
