### ISSUE TITLE
[BUG] "Sort" Button only sorts the top half of 2-block cabinets.

### ISSUE THREAD

**Issue by TortraxTR** [CalaMariGold/Rebirth-Of-The-Night#40]
**Describe the bug**
Cabinets stacked on top of each other make a vertical double chest, but the sort button only sorts what it considers the first half of the inventory.

**To Reproduce**
Stack 2 cabinets on top of each other, making a 2-block chest inventory.
Add random items, so that more than half the cabinet's inventory is full.
Click the sort button for the cabinet.

**Expected behavior**
Like a double chest, it should sort the entire inventory of the cabinet.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.74
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.74

**Comment by CalaMariGold** [comment]
This is an issue for Quark. https://github.com/Vazkii/Quark

**Comment by CalaMariGold** [comment]
Fixed in 2.77
