### ISSUE TITLE
[BUG] Endermen porting player inside blocks

### ISSUE THREAD

**Issue by thefire1995** [CalaMariGold/Rebirth-Of-The-Night#43]
**Describe the bug**
when fighting a endermen in a small pool warped me twice once was 5-7 block from my original position then some how warped me under ground
**To Reproduce**
fighting a endermen in a pool of water 1 block tall, ~5 blocks outward
**Expected behavior**
when fighting the endermen will warp you underground 

**Info (please complete the following information):**
Singleplayer modded version 2.75.1 world was made on 2.75.1

**Additional context**
had a copper spear and a torch out

**Comment by SandwichHorror** [comment]
Should be fixed in 2.75.2, disabled the Epic Siege option that was responsible.
