### ISSUE TITLE
[CRASH] Aechor Plants dart effects crash the game indefinitely

### ISSUE THREAD

**Issue by JuniKnytt** [CalaMariGold/Rebirth-Of-The-Night#46]
The effects from the Aether's poison dart freezes and crashes the game indefinitely, no matter what you do reloading the world promptly crashes it, rendering the world unusable.

Go into the Aether and get hit by specifically the Purple Aechor Plant's darts.

Upon getting hit the game will freeze immediately and then promptly crash.

Even pausing the game before the poison effect occurs will trigger the freeze.
![Capture](https://user-images.githubusercontent.com/42306249/73817151-20918000-479f-11ea-88fd-d10273efe97a.PNG)

 - ver. 2.74
 - Single Players
 - Created on version 2.74

The world is imported from a server I was hosting since no one wanted to continue the world.

**Comment by CalaMariGold** [comment]
Please provide a crash log or some kind of log.
