### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Buckwheatx1** [CalaMariGold/Rebirth-Of-The-Night#48]
**Describe the bug**
When you encounter an Ender blaze in the end (specifically when they shoot End Fireball), the game crashes completely. Image of crash issue: https://i.gyazo.com/thumb/1200/1f331dc78b7dc447f8ba186aee03284b-png.jpg

**To Reproduce**
1. Go into End dimension
2. Encounter purple/pink Ender blaze
3. Wait till Ender blaze shoots a fireball or game crash

**Expected behavior**
Game should crash, server would close following that. 

**Screenshots**
![image](https://user-images.githubusercontent.com/60735059/73925305-96215b80-4919-11ea-982f-efc00b61c0bd.png)
https://gyazo.com/1f331dc78b7dc447f8ba186aee03284b

**Info (please complete the following information):**
 - Modpack Version: 2.72 and we also tried 2.75
 - Server or Singleplayer: Server 
 - Version the world was created on: 2.72

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by CalaMariGold** [comment]
Fixed in one of the versions after 2.72.
