### ISSUE TITLE
[CRASH] After we killed the ender dragon the server started to crash repeatedly.

### ISSUE THREAD

**Issue by Sophia-Schuster** [CalaMariGold/Rebirth-Of-The-Night#51]
**Describe the bug**
The world is crashing even if we restart it. It crashed five times already! Here is the error: 
https://paste.dimdev.org/xusijoxeda.mccrash

**To Reproduce**
The last time we could use the world I was on LAN with my friend and passing by the end portal to come back to the normal world then the server crashed.

**Expected behavior**
I expected to come back to the normal world (get out of the end) normally. 

**Screenshots**
The world crashed now for the 6 time:
![image](https://user-images.githubusercontent.com/60801559/74076607-d820cf00-49f7-11ea-81b2-951f2f3e36fa.png)

**Info (please complete the following information):**
 - Modpack Version: 2.75.1
 - Server or Singleplayer: singleplayer but with LAN (we were on the same internet)
 - Version the world was created on: 2.72

**Additional context**
After we killed the ender dragon the server started to crash, maybe it is some problem with the end.
Or the changes after killing the ender dragon (like new stronger mobs).
 We tried to restart it, sometimes work but sometimes didn't. If we wait the world probably will work again, but after some minutes it will crash. 
It crashed five times already! (six now.)
This is not the first time we are having problems with the world crashing, the last time I was planting a tree in the creative mode and I had the same issue. But I started my world in a older version and came back to the new one and it was normal again. (We already tried this but didn't work this time)

 (Sorry for my english, I am Brazilian.)

**Comment by CalaMariGold** [comment]
While I don't know if this is the issue exactly (seeing as you got all the way to the ender dragon), LAN worlds do not work in RebN. Create a server using our server files or get a server from Akliz. You can then import your world.
