### ISSUE TITLE
[Crash] Server Crashes Randomly on Certain Chunk Loads

### ISSUE THREAD

**Issue by xl3lackout** [CalaMariGold/Rebirth-Of-The-Night#52]
[crash-2020-02-09_00.08.10-server.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4176507/crash-2020-02-09_00.08.10-server.txt)

The server just crashes with only the line [underground biomes] Stopping Server.
Happens only when we go towards the few chunks around our home, the crash file says something about pathfinding errors, but I'm not really sure.

**Comment by SandwichHorror** [comment]
Should be fixed in the next update or hotfix. Myrmex Royal code had issues with doorbreaking AI, so I've now removed it.
