### ISSUE TITLE
[CRASH] BOP-BWM Incompatibility

### ISSUE THREAD

**Issue by CallMeCar-Son** [CalaMariGold/Rebirth-Of-The-Night#54]
My friend and I are on a server we're hosting together and everything was going accordingly until all of a sudden our server just closed. and will continue to close every time we log in. i have a crash log and a screenshot of our base due to it _perhaps_ being the issue.
![2020-02-08_16 33 51](https://user-images.githubusercontent.com/60890245/74167976-ad4c9b80-4bee-11ea-9029-fcef23abcba3.png)
[message.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4181871/message.txt)

**Comment by CalaMariGold** [comment]
`biomesoplenty.api.enums.BOPWoods .....  as it does not exist in ExtendedBlockState{block=betterwithmods:siding_wood, properties=[]`

Some incompatibility between Better With Mods and BOP. BWM isn't being updated anymore, so it's unlikely it's fixable. Remove BWM and try joining. If it works, add it back in and try joining again.

**Comment by CalaMariGold** [comment]
Also next time please use our issues template.

**Comment by CallMeCar-Son** [comment]
sounds good. will update you on it. and sounds good, forgot to paste it
back in the format. thank you!

**Comment by HeyItsKairu** [comment]
Not much we can do about this, I doubt the BoP author would be able to fix this.

**Comment by CalaMariGold** [comment]
Well don't close it so that players dont recreate this issue on GitHub

**Comment by HeyItsKairu** [comment]
Why not close this and make a pinned issue about the incompatibilities between BoP and BWM?

**Comment by CalaMariGold** [comment]
Just because it's unfixable, doesn't mean it's an issue. You don't know for a fact if the mod dev won't fix it. The entire purpose of this issues page is to have a list of known issues and discuss them.

**Comment by CallMeCar-Son** [comment]
hey you guys, not sure if I'm supposed to still be pinned in this convo,
but with the latest release of version 2.75.3, it has been fixed due to the
change of the kiln system (which I believe is 10x better btw, great job
guys!)

**Comment by CalaMariGold** [comment]
Not sure how that fixed it. This issue is due to BWM and BOP, not pyrotech. But whatever you say!

**Comment by CallMeCar-Son** [comment]
well in our specific case, it was the fire under our kiln just closing the
server immediately, should have specified, my b
