### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by PrivatePile38** [CalaMariGold/Rebirth-Of-The-Night#55]
**Describe the bug**
I crash after about 15 seconds in my world

**To Reproduce**
I’m not sure. I was on day 21, and all of the sudden I began having this issue. 

**Expected behavior**
I expect to enter the game and be able to play 

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 1.75.1
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 1.75.1

**Additional context**
The problem started randomly, I had no previous issues with crashing. I’ve tried to restart my pc, the crash report says the cause is unknown.

**Comment by SandwichHorror** [comment]
You need to click the "Get Link" button and post the log here or this crash report is unfortunately useless.
