### ISSUE TITLE
[BUG] Possible issue with Lapis Lazuli Advancement

### ISSUE THREAD

**Issue by MaybeNotACow** [CalaMariGold/Rebirth-Of-The-Night#57]
Issue: 'We Can Enchant' advancement will not unlock after acquiring Lapis Lazuli.

Images attached:

One -
![Desktop Screenshot 2020 02 11 - 18 02 59 76](https://user-images.githubusercontent.com/60295319/74288421-5af8a100-4cfa-11ea-86f6-3fd712781bc2.png)

Two - 
![Desktop Screenshot 2020 02 11 - 18 03 10 69](https://user-images.githubusercontent.com/60295319/74288429-60ee8200-4cfa-11ea-908b-0002a0b496e5.png)

Three - 
![Desktop Screenshot 2020 02 11 - 18 03 15 75](https://user-images.githubusercontent.com/60295319/74288433-65b33600-4cfa-11ea-81df-efebdce49e5f.png)

Four - 
![Desktop Screenshot 2020 02 11 - 18 03 20 47](https://user-images.githubusercontent.com/60295319/74288454-6d72da80-4cfa-11ea-8125-12322749357f.png)

Five -
![Desktop Screenshot 2020 02 11 - 18 03 24 67](https://user-images.githubusercontent.com/60295319/74288462-6fd53480-4cfa-11ea-8840-fb2b2fe4a4cb.png)

Comment on images: The order is as follows - Ore is spotted in picture one; Picture two is taken immediately after to show that advancement has not been unlocked; Picture three is taken upon mining said ore block; Picture four is taken upon collecting the ore; Picture five is taken immediately after collection to display lack of advancement persisting.

Note: This is entirely just a report, as this does NOT derail the game, ruin immersion, or affect the gameplay, yet if one advancement is possibly bugged, it is my hope to report it and solve potential future issues.

Thank you.

**Comment by CalaMariGold** [comment]
I can't reproduce this. It works on my end, and I checked the code to make sure. Make sure you're on the latest version.
