### ISSUE TITLE
[BUG] Crash

### ISSUE THREAD

**Issue by PrivatePile38** [CalaMariGold/Rebirth-Of-The-Night#58]
**Describe the bug**
I crash after about 15 seconds after joining my world

**To Reproduce**
Unsure

**Expected behavior**
I suppose I expected it not to crash 

**Screenshots**
Here is the link to the crash report- https://paste.dimdev.org/bikeracebu.mccrash

**Info (please complete the following information):**
 - Modpack Version: 2.75.3
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.75.1

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by HeyItsKairu** [comment]
Myrmex mobs appear to be attempting to break doors which is an AI they should not have. Will look into fixing this for the next version.

**Comment by HeyItsKairu** [comment]
Fixed in latest version.
