### ISSUE TITLE
[BUG] Crash upon loading into game world

### ISSUE THREAD

**Issue by MaybeNotACow** [CalaMariGold/Rebirth-Of-The-Night#60]
**Describe the bug**
Unexplicable crash upon successful loading into game world.

**To Reproduce**
Load into this game world, not much else to be determined from this players end.

**Expected behavior**
To not crash upon loading into game world.

**Screenshots**

https://drive.google.com/open?id=1gwMyY05DNGbfYENdmWyYdKCa8Q6V_OF-

**Info (please complete the following information):**
 - Modpack Version: 2.75.3
 - Server or Singleplayer: Singplayer
 - Version the world was created on: 2.75.2

**Additional context**
Possibly related to a Skeleton shooting arrows at my character, whilst underwater holding a lantern? Uncertain.

Crash log - 

[crash-2020-02-11_22.47.23-client.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4195953/crash-2020-02-11_22.47.23-client.txt)

[crash-2020-02-12_18.32.05-client.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4195954/crash-2020-02-12_18.32.05-client.txt)

[crash-2020-02-12_18.36.26-client.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4195955/crash-2020-02-12_18.36.26-client.txt)

**Comment by HeyItsKairu** [comment]
Could you provide a crash log or a regular log if there is no crash?

**Comment by MaybeNotACow** [comment]
Apologies! Totally forgot, corrected!

**Comment by SandwichHorror** [comment]
Disable Emissive Textures in options while in the main menu (doing it while in a world causes a crash usually)

**Comment by CalaMariGold** [comment]
Emissive Textures should be automatically disabled in the newest version.
