### ISSUE TITLE
[BUG]Royal Myrex causes crash when near village

### ISSUE THREAD

**Issue by PrivatePile38** [CalaMariGold/Rebirth-Of-The-Night#61]
**Describe the bug**
I crash within a second, or before I load into the world

**To Reproduce**
Give a Myrex a reason to break a door

**Expected behavior**
The game to not crash 

**Screenshots**
https://paste.dimdev.org/zuqamehaqe.mccrash
Here is the report, but reading it, I believe this is the same issue.

**Info (please complete the following information):**
 - Modpack Version: 2.75.3
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.75.1

**Additional context**
I originally found this bug while exploring near a village. I eventually managed to stay in the world long enough to get off a /kill command by turning down my render distance. Later, I found a separate village, far away, and came across the same issue.

**Comment by CalaMariGold** [comment]
Fixed in 2.76 (for real this time)
