### ISSUE TITLE
[CRASH] Crash due to Rustic Cabinet

### ISSUE THREAD

**Issue by MaybeNotACow** [CalaMariGold/Rebirth-Of-The-Night#64]
**Describe the bug**
With no history of any issue with the Cabinets introduced via Rustic, a crash occurs upon loading into the game, and initially after retrieving an item from said Cabinet.

**To Reproduce**
Steps to reproduce the behavior: Try shift clicking materials into inventory from Cabinet quickly, whilst hitting escape and turning away from Cabinet.

**Expected behavior**
As stated, issue was unexpected, as I have used the Cabinets from Rustic extensively, and had no issue thus far.

**Screenshots**
N/A

**Info (please complete the following information):**
 - Modpack Version:  2.75.3
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.75.3

**Additional context**
N/A

Crashlogs:

[crash-2020-02-13_23.00.36-client.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4202646/crash-2020-02-13_23.00.36-client.txt)

[crash-2020-02-13_23.04.47-client.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4202647/crash-2020-02-13_23.04.47-client.txt)

[crash-2020-02-13_23.06.58-client.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4202648/crash-2020-02-13_23.06.58-client.txt)

[crash-2020-02-13_23.15.05-client.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4202649/crash-2020-02-13_23.15.05-client.txt)

**Comment by CalaMariGold** [comment]
Crash because of emissive textures, which we disabled in one of the recent patches. Should no longer crash.
