### ISSUE TITLE
[BUG] fruit trees drop fruit block

### ISSUE THREAD

**Issue by cole333333** [CalaMariGold/Rebirth-Of-The-Night#65]
**Describe the bug**
harvesting tree fruit drops both the fruit and the fruit block

**To Reproduce**
harvest a tree fruit.

**Expected behavior**
only the fruit drops 

**Info (please complete the following information):**
 - Modpack Version: 2.75.3
 - Server or Singleplayer: single
 - Version the world was created on: 2.75.2

**Comment by CalaMariGold** [comment]
I was able to reproduce this with hazelnut and pawpaw. Might be able to fix this by editing block drops, but it's unlikely. Either way, we'll try.

**Comment by kil0byt3** [comment]
https://github.com/MatrexsVigil/harvestcraft/issues/393

**Comment by democat3457** [comment]
Partially circumvented by giving them a use in 2895082b06e205ddc0dd4f67c650d04cd98328f1

**Comment by kil0byt3** [comment]
Great change, thanks for doing that

**Comment by kil0byt3** [comment]
Closed for now, doesn't seem like MatrexVigil is working on 1.12 HC anymore

**Comment by Nitro-Carwash** [comment]
This is an issue with Hunger Overhaul. I have a PR to fix this here: progwml6/HungerOverhaul#240
