### ISSUE TITLE
[BUG]ironberry flight

### ISSUE THREAD

**Issue by cole333333** [CalaMariGold/Rebirth-Of-The-Night#66]
**Describe the bug**
you can jump and fly with ironberrys

**To Reproduce**
eat an ironberry jump and jold jump

**Expected behavior**
you will fly up untill you let go of your jump key

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.75.3
 - Server or Singleplayer: single
 - Version the world was created on: 2.75.3

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by CalaMariGold** [comment]
... Yes. That's what ironberries do.

**Comment by cole333333** [comment]
is it intentional that you can fly to y 1000 wit 1 iron berry?

**Comment by CalaMariGold** [comment]
Yes that's what they do.
