### ISSUE TITLE
[BUG] Pam's Harvestcraft Well does not drop as an item

### ISSUE THREAD

**Issue by ThomBern** [CalaMariGold/Rebirth-Of-The-Night#67]
**Describe the bug**
The well block from Pam's does not give you its item form when you break it with a pickaxe

**To Reproduce**
Craft a Well, place it down, and break it with any pickaxe.

**Expected behavior**
The Well block should drop its item form, since it is craftable, and part of the Base Defense achievements.

**Info (please complete the following information):**
 - Modpack Version:  2.75.3
 - Singleplayer
 - 1.12.2 (?)

**Comment by CalaMariGold** [comment]
Intended.
