### ISSUE TITLE
[BUG] On a Hamachi LAN server, Hibachi seems to crash the world sometimes

### ISSUE THREAD

**Issue by EaiteSuper** [CalaMariGold/Rebirth-Of-The-Night#68]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 
 - Server or Singleplayer:
 - Version the world was created on:

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by CalaMariGold** [comment]
You literally didn't even provide anything in the description. What am I supposed to do with this??

**Comment by EaiteSuper** [comment]
The issue seems to be the same as this bug report
https://github.com/CalaMariGold/Rebirth-Of-The-Night/issues/28

Sorry for the lack of information. I was trying to figure out a solution to save the server world.
