### ISSUE TITLE
[CRASH] BWM Wood Siding Crash (BOP)

### ISSUE THREAD

**Issue by Xpeerius** [CalaMariGold/Rebirth-Of-The-Night#69]
**Describe the bug**
game crashes at start
**To Reproduce**
me and my friend just played the game and when we started windmilling the netherrack, we got achievment "cuddly friend" and ghast appeared in our snowy biom and sudennly minecraft crashed and got an error and i cannot start the world again.
**Expected behavior**
i wouldnt expect the game to crash after starting

**Screenshots**
https://media.discordapp.net/attachments/620840315502198785/678406056426209290/unknown.png?width=1088&height=677

**Info (please complete the following information):**
 - Modpack Version: 2.75.3
 - Server or Singleplayer: Singleplayer 
 - Version the world was created on: 2.75.3

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by CalaMariGold** [comment]
Crash log?

**Comment by Xpeerius** [comment]
> Crash log?

I am so sorry, here it is https://paste.dimdev.org/axemijoyod.mccrash

**Comment by Xpeerius** [comment]
Unfortunatelly even after the last update ive still got the same issue :(

**Comment by CalaMariGold** [comment]
I was able to reproduce this. It occurs when Siding using Biomes O Plenty wood is set on fire. We MAY be able to fix this by making these blocks have zero flammability. If not, we may have to disable siding using BOP wood.

**Comment by CalaMariGold** [comment]
@HeyItsKairu Has submitted an issue about this some time ago. https://gitlab.com/BetterWithMods/1.12/BetterWithMods/issues/1347

**Comment by democat3457** [comment]
https://gitlab.com/BetterWithMods/1.12/BetterWithMods/-/merge_requests/977 opened pr for the issue

**Comment by democat3457** [comment]
pr has been merged into bwm gitlab

**Comment by democat3457** [comment]
Fixed by a387e168ff67989230e5b6d2c92517726f70bac0
