### ISSUE TITLE
[BUG] Dynamic Trees have missing textures on world join

### ISSUE THREAD

**Issue by CalaMariGold** [CalaMariGold/Rebirth-Of-The-Night#70]
**Describe the bug**
Dynamic Trees have missing textures on world join

**To Reproduce**
Unsure. Might have something to do with enabling/disabling shaders.

**Expected behavior**
Proper textures.

**Info (please complete the following information):**
 - Modpack Version: 2.75.3
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.75.3

**Additional context**
Fixed by restarting Minecraft and rejoining the world.

**Comment by kil0byt3** [comment]
Stale, likely not a huge issue, restarting MC fixes
