### ISSUE TITLE
[BUG] Twilight Forest has a white sky with shaders

### ISSUE THREAD

**Issue by CalaMariGold** [CalaMariGold/Rebirth-Of-The-Night#71]
**Describe the bug**
When shaders are enabled (tested with silders default), the TF sky will be white.

**To Reproduce**
Enable shaders (silders advanced default), go into the Twilight Forest.

**Expected behavior**
A not broken sky.

**Screenshots**
![image](https://user-images.githubusercontent.com/57605926/74599172-e69c6580-504b-11ea-9a0e-02551517823b.png)

**Info (please complete the following information):**
 - Modpack Version: 2.75.3
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.75.3

**Additional context**
Appears to switch back to normal depending on the direction you are facing.

**Comment by kil0byt3** [comment]
Shader bug, can't fix unless we get some custom shader work - @PC-TimeST is working on some stuff
