### ISSUE TITLE
[CRASH] When joining my world, I still crash with potioncore and sometimes other mods.

### ISSUE THREAD

**Issue by MegaMan0429** [CalaMariGold/Rebirth-Of-The-Night#72]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
With the 2.7.6.1 update fixing potioncore crashing, it still happens. Sometimes, even other mods are the reason my world crashes every attempt I join the world.

**To Reproduce**
Join the world and wait for crash to happen or it will happen immediately.

**Crash Log**
[crash-2020-02-17_17.07.05-server.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4216532/crash-2020-02-17_17.07.05-server.txt)

**Info (please complete the following information):**
 - Modpack Version: 2.76.1
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.75.2

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by CalaMariGold** [comment]
Try creating a new world and see if this still occurs.

**Comment by MegaMan0429** [comment]
New world works fine.
