### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by Gamerlord** [CalaMariGold/Rebirth-Of-The-Night#76]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
The game crashes close to the end of initial loading. Apparently the problem mod is B3M

**To Reproduce**
Run the game? I don't know.
**Crash Log**
Click "Get Link" from the crash and paste it here. Or post the log if it's a server.
https://paste.dimdev.org/qesujibano.mccrash
![image](https://user-images.githubusercontent.com/6385665/74701865-22a41600-5258-11ea-9f37-24230b13f811.png)

**Info (please complete the following information):**
 - Modpack Version: 2.76.1
 - Server or Singleplayer: N/A
 - Version the world was created on: N/A

**Additional context**
This is not just happening to me, others have reported getting to this crash screen, albeit with different mods being the problem.

**Comment by Xpeerius** [comment]
Yeah i am having same problems with modes Biomes o Plenty and Better with modes, hopefuly its gonna be ok soon.

**Comment by Balufire** [comment]
I have the same issue as OP:  Crash during start up, ~97%.  Crashlog indicates B3M.  Twitch User
[https://paste.dimdev.org/nanihediya.mccrash](https://paste.dimdev.org/nanihediya.mccrash)

**Info:**
Modpack Version 2.76.1

**Additional context**
I've done some troubleshooting to try and find the issue: 
- Repaired the modpack
- Reinstalled the modpack
- Updated Optifine to F5
- Used clean B3M jar from B3M page.
- Installed 2.76 then updated to 2.76.1
- Deleted profile folder manually and reinstalled.  https://paste.dimdev.org/dulehocawo.mccrash
(new log as I was doing the last point while typing this.)

I have minor variations of the Crashlog, some indicating different errors but all of them indicate B3M as the most likely culprit.

**Comment by CalaMariGold** [comment]
Fixed in 2.77
