### ISSUE TITLE
[CRASH] Inserting a damaged enchanted tool/weapon in the Vanilla anvil crashes the game

### ISSUE THREAD

**Issue by ThomBern** [CalaMariGold/Rebirth-Of-The-Night#77]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
The crash happens when you insert a damaged AND enchanted tool or weapon in the left-most slot of the Vanilla anvil, THEN insert any other enchanted tool in the center slot. The crash shuts down the internal server, and brings you back to the main menu.

**To Reproduce**

Have an damaged and enchanted tool/weapon (I had a silver pickaxe and a diamond sword when the crashes happened).
Place that tool in the left-most slot of the vanilla anvil.
Place a tool of the same type (this one should not be damaged, but still enchanted) in the center slot of the anvil.
The crash should happen*

**Crash Log**
[Anvil crash.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4220645/Anvil.crash.txt)

**Info (please complete the following information):**
 - Modpack Version: 2.76
 - Singleplayer
 - 1.12.2

**Additional context**
*P.S.: I tried to recreate the crash with an iron pickaxe, but it didn't crash like I intended it to, so the problem might be with the amount of XP levels needed to repair said tool.

**Comment by CalaMariGold** [comment]
I wasn't able to reproduce this with the steps you outlined, even with trying other things and making the cost super high. Might've been a rare one time thing.
