### ISSUE TITLE
[BUG] Cannot Craft Skyroot Handles

### ISSUE THREAD

**Issue by AlasEyrd** [CalaMariGold/Rebirth-Of-The-Night#78]
**Describe the bug**
Four skyroot sticks and one leather does not craft Skyroot Handles, it crafts normal Handles.

**To Reproduce**
Steps to reproduce the behavior: Put four skyroot sticks and leather into the crafting table. It will craft normal Handles.

**Expected behavior**
Four Skyroot sticks and a leather is expected to craft Skyroot Handles.

**Screenshots**
https://ibb.co/C1SRhvP
https://ibb.co/sChs5Yd

**Info (please complete the following information):**
 - Modpack Version: 2.76.1
 - Server or Singleplayer: Tested on both
 - Version the world was created on: 2.75.3

**Additional context**
Checked in singleplayer and multiplayer, the scripts are up to date on both server and client.

**Comment by cutcat101** [comment]
Fixed in next update
thanks
