### ISSUE TITLE
[BUG]Visual Glitches

### ISSUE THREAD

**Issue by Tip0fTheIceberg** [CalaMariGold/Rebirth-Of-The-Night#81]
When I join a world, my player model spazzes out and the arms and legs start flying everywhere.  Furthermore, when I try to run forward it pans way far out to the point where I can't see anything and zooms back to normal when I stop running.

It's been happening every time I launch Rebirth of Night today.  It worked fine until I installed optifine 1.12.2 F4, but since then it has been crazy.

I expected it to work as usual with normal controls

**Info (please complete the following information):**
 - Modpack Version: 2.76.1
 - Server or Singleplayer: Server
 - Version the world was created on: 2.75.3

**Additional context**
It worked fine without optifine, but I need optifine to apparently run the pack and get passable FPS

It doesn't seem to be letting me attach a video

**Comment by CalaMariGold** [comment]
This is an issue with forge/minecraft. The solutions for it are on google.
