### ISSUE TITLE
weapons and tools not having full textures

### ISSUE THREAD

**Issue by FoxKingLD** [CalaMariGold/Rebirth-Of-The-Night#82]
[https://cdn.discordapp.com/attachments/620849502558879785/680221261606944813/2020-02-20_20.04.29.png](url) the tools and weapons haven't been 3D and have been just 2D paper textures

**Comment by CalaMariGold** [comment]
Install optifine and make sure both texture packs are enabled.

**Comment by FoxKingLD** [comment]
I do use optifine
