### ISSUE TITLE
[BUG] Severly high health/damage of twilight forest mobs

### ISSUE THREAD

**Issue by jaimejaime19** [CalaMariGold/Rebirth-Of-The-Night#83]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Sometimes, Twilight Forest mobs will spawn with an absurd amount of health and damage. 
**To Reproduce**
Go to the Twilight Forest, then find a Minoshroom/Phantom Knight maze, or Ur-Ghast tower. Search around for some Twilight Forest-specific mobs, such as fire beetle, slime beetle, kobold, block and chain goblins, carminite golems and ghasts.
**Expected behavior**
In the Minoshroorm maze, slime/fire beetles spawn with health amounting to 156.25, 312.5, and 390.38 hp. Their damage is a lot more than what it should be. In the phantom knight maze, mobs spawn with even higher health, reaching about 512 and 1024hp for the kobolds, hermit crabs, and block and chain goblins. The ur-ghast tower has the same issue for health and damage of carminite golems and ghasts.
**Screenshots**
![1171](https://user-images.githubusercontent.com/60041231/75086089-66fc1400-54ed-11ea-9620-4aad1bc93024.png)
![2048](https://user-images.githubusercontent.com/60041231/75086092-6cf1f500-54ed-11ea-83bf-9960f6242c19.png)

**Info (please complete the following information):**
 - Modpack Version: 2.76.1
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.76.1

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.
This was all tested on creative. It seems to only affect Twilight mobs in my experience.

**Comment by CalaMariGold** [comment]
This is mostly intended. We'll look into specific mob health down the line. The Twilight Forest is an end-game dimension, meaning you should be doing hundreds of damage per hit.
