### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ChewyGogurt** [CalaMariGold/Rebirth-Of-The-Night#84]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
I can only place blocks for a little bit before it stops. When I try to place the block shows up and disappears along with taking a block out of my inv. 

**To Reproduce**
I have no idea, I was screen sharing on discord with a chrome tab open. 

**Expected behavior**
After reloading my world it works for a minute then it stops showing the blocks I'm "placing" but takes one away.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.76.1
 - Server or Singleplayer: singleplayer
 - Version the world was created on: 2.76.1

**Additional context**
Still happens after I restart my game. I was talking on discord while screensharing, my game seems more laggy, and I had joined my friends server before getting on singleplayer.

**Comment by CalaMariGold** [comment]
Sounds like you're lagging. Reinstall the modpack and don't screenshare or anything.
