### ISSUE TITLE
Server launching crash about "BetterWithMods" mod[CRASH]

### ISSUE THREAD

**Issue by oytunocal** [CalaMariGold/Rebirth-Of-The-Night#85]
When i try the launch server it errors with only "betterwithmods" mod

I cleaned and reinstalled my ALL java things

[crash-2020-02-22_19.17.54-server.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4239691/crash-2020-02-22_19.17.54-server.txt)

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_241, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 2934271000 bytes (2798 MB) / 4096786432 bytes (3907 MB) up to 4096786432 bytes (3907 MB)
  JVM Flags: 2 total; -Xmx4096M -Xms4096M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 172 mods loaded, 172 mods active

**Comment by CalaMariGold** [comment]
Please create a new issue using our format.
