### ISSUE TITLE
[BUG]Wrought Axe Taking Durability Damage

### ISSUE THREAD

**Issue by capio13** [CalaMariGold/Rebirth-Of-The-Night#86]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
When I died while having the Wrought Axe and the Wrought Helmet equipped, the wrought helmet didn't take any durability damage, but the wrought axe did even though both are never supposed to break.

**To Reproduce**
Die with the Wrought Axe in your hotbar and the Wrought Helmet in

**Expected behavior**
I was expecting neither to take durability damage since in the tool tip it says it never breaks.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.76
 - Server or Singleplayer:Singleplayer
 - Version the world was created on:2.76

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by CalaMariGold** [comment]
Intended. We'll fix the tooltip eventually
