### ISSUE TITLE
[CRASH] Set Bonus Crash

### ISSUE THREAD

**Issue by ChewyGogurt** [CalaMariGold/Rebirth-Of-The-Night#87]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
2 crashes, i went to the aether the first time then broke a berry bush and crashed. The second time i was building to a silver dungeon after going through one with no boss. it then crashed and brought me to the launcher.

**To Reproduce**

Idk the aether maybe?

**Crash Log**
Click "Get Link" from the crash and paste it here. Or post the log if it's a server.
[crash-2020-02-22_20.49.21-server.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4240596/crash-2020-02-22_20.49.21-server.txt)

[crash-2020-02-22_20.57.22-client.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4240597/crash-2020-02-22_20.57.22-client.txt)

**Info (please complete the following information):**
 - Modpack Version: 2.76.1
 - Server or Singleplayer: Single
 - Version the world was created on: 2.76.1

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by CalaMariGold** [comment]
Does your world perma crash?
