### ISSUE TITLE
[BUG] Drafthorse sometimes vanishes when dismounting.

### ISSUE THREAD

**Issue by sspazzy** [CalaMariGold/Rebirth-Of-The-Night#88]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Draft horse stallion vanishing when dismounting randomly 

**To Reproduce**
Shift to dismount I think. I cannot think of any specific differences when it happens compared to when it doesn't

**Expected behavior**
Horse does not vanish

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.76.1
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.76.1

**Additional context**
To fix it I have to reload the world (save and exit) and the horse appears where I dismounted.

**Comment by CalaMariGold** [comment]
This is a vanilla bug in 1.12 and even newer versions.
