### ISSUE TITLE
[BUG]Infinite jelly (Royal/luminous)

### ISSUE THREAD

**Issue by LuciferPebble** [CalaMariGold/Rebirth-Of-The-Night#90]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Theres a bug involving the harvest craft queen bee id#9272 and Mowziesmobs Luminous Jelly Id#6775 the bug involves the queen not getting used up and duping the luminous Jelly 
**To Reproduce**
put more then 1 jelly (3+ starts to make extra jelly) into your crafting grid with 1 queen bee and take royal jelly
**Expected behavior**
the queen will be put into your inventory and the jelly will increase in size can be done "Endlessly" to get infinite Royal and Luminous Jelly from 1 queen
**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.76.1
 - Server or Singleplayer: Server
 - Version the world was created on: 2.75.3

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.
![20200226_021226](https://user-images.githubusercontent.com/60997575/75321147-2a5a5080-583e-11ea-90dd-488d11d5985e.jpg)

**Comment by SandwichHorror** [comment]
Fixed in next update. New recipe and non-dupeable queen.
