### ISSUE TITLE
[BUG] Limestone slabs textures missing in server only.

### ISSUE THREAD

**Issue by theheckromancer** [CalaMariGold/Rebirth-Of-The-Night#92]
**Describe the bug**
Limestone slabs textures are missing if thrown on the ground or looking at through WAILA, it is not
missing any textures when placed or looking at through the inventory. I could only replicate it through my server and not single player, both of which were downloaded as version 2.76.1.

**To Reproduce**
Use both texture packs on a server, then drop limestone slab onto ground. Also, place a limestone slab, look at the bottom left for the WAILA information and notice the missing texture.

**Expected behavior**
For them to not have a missing texture.

**Screenshots:**
https://i.imgur.com/JYk6Ajb.png
https://i.imgur.com/DEi72zb.png

**Info:**
 - Modpack Version: 2.76.1
 - Server or Singleplayer: Server
 - Version the world was created on: 2.76.1

**Additional context:**
I tried deleting the resource packs from the server's resource pack folder, which didn't fix the problem, and the texture shows up in single player so I'm not sure what to think. I also tried re-downloading and using the new resource pack files, but that didn't fix the problem either. I tested this with a few other stone slabs but not all of them, didn't notice anything weird with the few samples I did check.

**Comment by CalaMariGold** [comment]
I was able to reproduce this on singleplayer. Seems like faulty coding. Will see post this in the Underground Biomes github. Is not a waila issue.

https://github.com/Aang23/UndergroundBiomesConstructs/issues/216

**Comment by kil0byt3** [comment]
Should be fixed in upcoming mod version as per https://github.com/Aang23/UndergroundBiomesConstructs/issues/216
