### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by EduardKhil** [CalaMariGold/Rebirth-Of-The-Night#95]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Apologies, I thought the text was automated form GitHub not a template. 
Unsure, seems random - just says press ctrl + I

**To Reproduce**
Seems something to do with the nether - however whenever i log off it shows it on the screen. We are on a server.

**Expected behavior**
Not display the error :-)

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: current. 2.76.1
 - Server or Singleplayer: server 
 - Version the world was created on: 2.75.3

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.
Seems to have something to do with the nether maybe? It just loops until i log. 
https://paste.dimdev.org/oqujorepoy.mccrash

**Comment by CalaMariGold** [comment]
Very generic error report that we can't do anything about with this little information. Sorry
