### ISSUE TITLE
[BUG]Void Forge

### ISSUE THREAD

**Issue by JunoYuno** [CalaMariGold/Rebirth-Of-The-Night#96]
When void forges are placed against a block it causes said block to become invisible and allow you to see through the world

Build a void forge and place it against a block

Possible abuse of said bug, to discover caves or other things underground

![image](https://user-images.githubusercontent.com/61574135/75512831-b0060980-59c0-11ea-81fd-bd4d84d91079.png)

**Info (please complete the following information):**
 - Modpack Version: 1.12.2
 - Server or Singleplayer: Server
 - Version the world was created on: 1.12.2

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by CalaMariGold** [comment]
"Modpack Version: 1.12.2"

That is not the version of the modpack.

Either way, this goes to the Endreborn developer, which is no longer updating the mod (it seems).
