### ISSUE TITLE
[CRASH] Aqueducts w/water bucket

### ISSUE THREAD

**Issue by deebyte** [CalaMariGold/Rebirth-Of-The-Night#99]
**Describe the crash**
Just testing Aqueducts in server. Yes it causes crash every time world starts, after a few seconds - but world can be saved if water can be removed fast enough, so the crash happens when the world ticks the water I assume? Survival and Creative

**To Reproduce**

1. Place a length of Aqueducts down with walls
2. Place water in with a bucket
3. Crash

**Crash Log**
https://paste.dimdev.org/egovolohuk.mccrash

**Info (please complete the following information):**
 - Modpack Version: 2.76
 - Server or Singleplayer: Both
 - Version the world was created on: 2.76

**Additional context**
Potential linked commit: https://github.com/CalaMariGold/Rebirth-Of-The-Night/commit/2ff513281fb0d47b7f42641f544c2e39a8af233c

**Comment by CalaMariGold** [comment]
Fixed in the next version. 2.76.2(?)
